DROP DATABASE IF EXISTS nobsc;

CREATE DATABASE nobsc;

USE nobsc;



CREATE TABLE cuisines (
  `id`        tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `continent` varchar(2)       NOT NULL DEFAULT '',
  `code`      varchar(3)       NOT NULL DEFAULT ''  UNIQUE,
  `name`      varchar(40)      NOT NULL DEFAULT '',
  `country`   varchar(40)      NOT NULL DEFAULT ''  UNIQUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE equipment_types (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ingredient_types (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE measurements (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE methods (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE product_categories (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE product_types (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recipe_types (
  `id`   tinyint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(25)               DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE suppliers (
  `id`   smallint unsigned NOT NULL DEFAULT '0' PRIMARY KEY,
  `name` varchar(60)       NOT NULL             UNIQUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- We use AUTO_INCREMENTing PKs for now, but if needed later, we will likely switch to UUIDv7

CREATE TABLE customers (
  `id`    int unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT ,
  `email` varchar(60)  NOT NULL UNIQUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE staff (
  `id`                int unsigned NOT NULL              PRIMARY KEY AUTO_INCREMENT,
  `email`             varchar(60)  NOT NULL              UNIQUE,
  `pass`              char(60)     NOT NULL,
  `staffname`         varchar(20)  NOT NULL              UNIQUE,
  `confirmation_code` varchar(255)          DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE users (
  `id`                int unsigned NOT NULL              PRIMARY KEY AUTO_INCREMENT,
  `email`             varchar(60)  NOT NULL              UNIQUE,
  `pass`              char(60)     NOT NULL,
  `username`          varchar(20)  NOT NULL              UNIQUE,
  `confirmation_code` varchar(255)          DEFAULT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE equipment (
  `id`                smallint unsigned NOT NULL             PRIMARY KEY AUTO_INCREMENT,
  `equipment_type_id` tinyint unsigned  NOT NULL DEFAULT '0',
  `author_id`         int unsigned      NOT NULL,
  `owner_id`          int unsigned      NOT NULL,
  `name`              varchar(100)      NOT NULL,
  `description`       text              NOT NULL,
  `image`             varchar(100)      NOT NULL DEFAULT '',
  FOREIGN KEY (`equipment_type_id`) REFERENCES `equipment_types` (`id`),
  FOREIGN KEY (`author_id`)         REFERENCES `users` (`id`),
  FOREIGN KEY (`owner_id`)          REFERENCES `users` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ingredients (
  `id`                 smallint unsigned NOT NULL             PRIMARY KEY AUTO_INCREMENT,
  `ingredient_type_id` tinyint unsigned  NOT NULL DEFAULT '0',
  `author_id`          int unsigned      NOT NULL,
  `owner_id`           int unsigned      NOT NULL,
  `brand`              varchar(50)       NOT NULL DEFAULT '',
  `variety`            varchar(50)       NOT NULL DEFAULT '',
  `name`               varchar(50)       NOT NULL DEFAULT '',
  `fullname`           varchar(152) GENERATED ALWAYS AS (CONCAT(brand, ' ', variety, ' ', name)),
  `alt_names`          json                       DEFAULT NULL,
  `description`        text              NOT NULL,
  `image`              varchar(100)      NOT NULL DEFAULT '',
  FOREIGN KEY (`ingredient_type_id`) REFERENCES `ingredient_types` (`id`),
  FOREIGN KEY (`owner_id`)           REFERENCES `users` (`id`),
  FOREIGN KEY (`author_id`)          REFERENCES `users` (`id`) 
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE orders (
  `id`          int unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `customer_id` int unsigned NOT NULL,
  `staff_id`    int unsigned NOT NULL,
  FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  FOREIGN KEY (`staff_id`)    REFERENCES `staff` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE plans (
  `id`        int unsigned NOT NULL            PRIMARY KEY AUTO_INCREMENT,
  `author_id` int unsigned NOT NULL,
  `owner_id`  int unsigned NOT NULL,
  `name`      varchar(100) NOT NULL DEFAULT '',
  `data`      json DEFAULT NULL,
  FOREIGN KEY (`author_id`) REFERENCES `users` (`id`),
  FOREIGN KEY (`owner_id`)  REFERENCES `users` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE products (
  `id`                  smallint unsigned NOT NULL              PRIMARY KEY AUTO_INCREMENT,
  `product_category_id` tinyint unsigned  NOT NULL DEFAULT '0',
  `product_type_id`     tinyint unsigned  NOT NULL DEFAULT '0',
  `brand`               varchar(50)       NOT NULL DEFAULT '',
  `variety`             varchar(50)       NOT NULL DEFAULT '',
  `name`                varchar(50)       NOT NULL DEFAULT '',
  `fullname`            varchar(152) GENERATED ALWAYS AS (CONCAT(brand, ' ', variety, ' ', name)),
  `alt_names`           json                       DEFAULT NULL,
  `description`         text              NOT NULL,
  `specs`               json                       DEFAULT NULL,
  `image`               varchar(100)      NOT NULL DEFAULT '',
  FOREIGN KEY (`product_category_id`) REFERENCES `product_categories` (`id`),
  FOREIGN KEY (`product_type_id`)     REFERENCES `product_types` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recipes (
  `id`                int unsigned     NOT NULL            PRIMARY KEY AUTO_INCREMENT,
  `recipe_type_id`    tinyint unsigned NOT NULL,
  `cuisine_id`        tinyint unsigned NOT NULL,
  `author_id`         int unsigned     NOT NULL,
  `owner_id`          int unsigned     NOT NULL,
  `title`             varchar(100)     NOT NULL DEFAULT '',
  `description`       varchar(150)     NOT NULL DEFAULT '',
  `active_time`       time             NOT NULL,
  `total_time`        time             NOT NULL,
  `directions`        text             NOT NULL,
  `recipe_image`      varchar(100)     NOT NULL DEFAULT '',
  `equipment_image`   varchar(100)     NOT NULL DEFAULT '',
  `ingredients_image` varchar(100)     NOT NULL DEFAULT '',
  `cooking_image`     varchar(100)     NOT NULL DEFAULT '',
  `video`             varchar(100)     NOT NULL DEFAULT '',
  FOREIGN KEY (`recipe_type_id`) REFERENCES `recipe_types` (`id`),
  FOREIGN KEY (`cuisine_id`)     REFERENCES `cuisines` (`id`),
  FOREIGN KEY (`author_id`)      REFERENCES `users` (`id`),
  FOREIGN KEY (`owner_id`)       REFERENCES `users` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE favorite_recipes (
  `user_id`   int unsigned NOT NULL,
  `recipe_id` int unsigned NOT NULL,
  FOREIGN KEY (`user_id`)   REFERENCES `users` (`id`),
  FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE friendships (
  `user_id`   int unsigned NOT NULL,
  `friend_id` int unsigned NOT NULL,
  `status`    varchar(20)  NOT NULL,
  FOREIGN KEY (`user_id`)   REFERENCES `users` (`id`),
  FOREIGN KEY (`friend_id`) REFERENCES `users` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE order_products (
  `order_id`   int unsigned      NOT NULL,
  `product_id` smallint unsigned NOT NULL,
  FOREIGN KEY (`order_id`)   REFERENCES `orders` (`id`),
  FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE product_suppliers (
  `product_id`  smallint unsigned NOT NULL,
  `supplier_id` smallint unsigned NOT NULL,
  FOREIGN KEY (`product_id`)  REFERENCES `products` (`id`),
  FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recipe_equipment (
  `recipe_id`    int unsigned      NOT NULL,
  `amount`       tinyint unsigned  NOT NULL,
  `equipment_id` smallint unsigned NOT NULL,
  FOREIGN KEY (`recipe_id`)    REFERENCES `recipes` (`id`),
  FOREIGN KEY (`equipment_id`) REFERENCES `equipment` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recipe_ingredients (
  `recipe_id`      int unsigned      NOT NULL DEFAULT '0',
  `amount`         decimal(5,2)      NOT NULL,
  `measurement_id` tinyint unsigned  NOT NULL,
  `ingredient_id`  smallint unsigned NOT NULL DEFAULT '0',
  FOREIGN KEY (`recipe_id`)      REFERENCES `recipes` (`id`),
  FOREIGN KEY (`measurement_id`) REFERENCES `measurements` (`id`),
  FOREIGN KEY (`ingredient_id`)  REFERENCES `ingredients` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recipe_methods (
  `recipe_id` int unsigned     NOT NULL,
  `method_id` tinyint unsigned NOT NULL,
  FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`),
  FOREIGN KEY (`method_id`) REFERENCES `methods` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recipe_subrecipes (
  `recipe_id`      int unsigned     NOT NULL,
  `amount`         decimal(5,2)     NOT NULL,
  `measurement_id` tinyint unsigned NOT NULL,
  `subrecipe_id`   int unsigned     NOT NULL,
  FOREIGN KEY (`recipe_id`)      REFERENCES `recipes` (`id`),
  FOREIGN KEY (`measurement_id`) REFERENCES `measurements` (`id`),
  FOREIGN KEY (`subrecipe_id`)   REFERENCES `recipes` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE saved_recipes (
  `user_id`   int unsigned NOT NULL,
  `recipe_id` int unsigned NOT NULL,
  FOREIGN KEY (`user_id`)   REFERENCES `users` (`id`),
  FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



INSERT INTO staff (email, pass, staffname) VALUES
("tjalferes@tjalferes.com", "$2b$10$t9rf/EFZEq9Pno49TaYwnOmILd8Fl64L2GTZM1K8JvHqquILnkg5u", "T. J. Alferes");

INSERT INTO users (email, pass, username) VALUES
("tjalferes@tjalferes.com", "$2b$10$t9rf/EFZEq9Pno49TaYwnOmILd8Fl64L2GTZM1K8JvHqquILnkg5u", "NOBSC"),
("tjalferes@gmail.com",     "$2b$10$t9rf/EFZEq9Pno49TaYwnOmILd8Fl64L2GTZM1K8JvHqquILnkg5u", "Unknown"),
("testman@testman.com",     "$2b$10$t9rf/EFZEq9Pno49TaYwnOmILd8Fl64L2GTZM1K8JvHqquILnkg5u", "Testman");

INSERT INTO equipment_types (id, name) VALUES (1, "Cleaning"), (2, "Preparing"), (3, "Cooking"), (4, "Dining"), (5, "Storage");

INSERT INTO ingredient_types (id, name) VALUES
(1,  "Fish"),
(2,  "Shellfish"),
(3,  "Beef"),
(4,  "Pork"),
(5,  "Poultry"),
(6,  "Egg"),
(7,  "Dairy"),
(8,  "Oil"),
(9,  "Grain"),
(10, "Bean"),
(11, "Vegetable"),
(12, "Fruit"),
(13, "Nut"),
(14, "Seed"),
(15, "Spice"),
(16, "Herb"),
(17, "Acid"),
(18, "Product");

INSERT INTO measurements (id, name) VALUES
(1,  "teaspoon"),
(2,  "Tablespoon"),
(3,  "cup"),
(4,  "ounce"),
(5,  "pound"),
(6,  "milliliter"),
(7,  "liter"),
(8,  "gram"),
(9,  "kilogram"),
(10, "NA");

INSERT INTO methods (id, name) VALUES
(1,  "No-Cook"),
(2,  "Chill"),
(3,  "Freeze"),
(4,  "Microwave"),
(5,  "Toast"),
(6,  "Steam"),
(7,  "Poach"),
(8,  "Simmer"),
(9,  "Boil"),
(10, "Blanch"),
(11, "Stew"),
(12, "Braise"),
(13, "Bake"),
(14, "Roast"),
(15, "Broil"),
(16, "Saute"),
(17, "Pan-Fry"),
(18, "Shallow-Fry"),
(19, "Deep-Fry"),
(20, "Stir-Fry"),
(21, "Glaze"),
(22, "BBQ"),
(23, "Grill"),
(24, "Smoke");

INSERT INTO recipe_types (id, name) VALUES
(1,  "Drink"),
(2,  "Appetizer"),
(3,  "Main"),
(4,  "Side"),
(5,  "Dessert"),
(6,  "Soup"),
(7,  "Salad"),
(8,  "Stew"),
(9,  "Casserole"),
(10, "Sauce"),
(11, "Dressing"),
(12, "Condiment");

INSERT INTO cuisines (id, continent, code, name, country) VALUES
(1,  "AF", "DZA", "Algerian",                 "Algeria"),
(2,  "AF", "AGO", "Angolan",                  "Angola"),
(3,  "AF", "BEN", "Benin",                    "Benin"),
(4,  "AF", "BWA", "Botswana",                 "Botswana"),
(5,  "AF", "BFA", "Burkinabe",                "Burkina Faso"),
(6,  "AF", "BDI", "Burundian",                "Burundi"),
(7,  "AF", "CPV", "Cape Verdean",             "Cabo Verde"),
(8,  "AF", "CMR", "Cameroonian",              "Cameroon"),
(9,  "AF", "CAF", "Central African Republic", "Central African Republic"),
(10, "AF", "TCD", "Chadian",                  "Chad"),
(11, "AF", "COM", "Comoros",                  "Comoros"),
(12, "AF", "COD", "Congolese (Democratic)",   "Congo, Democratic Republic of the"),
(13, "AF", "COG", "Congolese",                "Congo, Republic of the"),
(14, "AF", "CIV", "Ivorian",                  "Côte d'Ivoire"),
(15, "AF", "DJI", "Djiboutian",               "Djibouti"),
(16, "AF", "EGY", "Egyptian",                 "Egypt"),
(17, "AF", "GNQ", "Equatorial Guinea",        "Equatorial Guinea"),
(18, "AF", "ERI", "Eritrean",                 "Eritrea"),
(19, "AF", "SWZ", "Eswatini",                 "Eswatini"),
(20, "AF", "ETH", "Ethiopian",                "Ethiopia"),
(21, "AF", "GAB", "Gabonese",                 "Gabon"),
(22, "AF", "GMB", "Gambian",                  "Gambia"),
(23, "AF", "GHA", "Ghanaian",                 "Ghana"),
(24, "AF", "GIN", "Guinea",                   "Guinea"),
(25, "AF", "GNB", "Guinea-Bissauan",          "Guinea-Bissau"),
(26, "AF", "KEN", "Kenyan",                   "Kenya"),
(27, "AF", "LSO", "Basotho",                  "Lesotho"),
(28, "AF", "LBR", "Liberian",                 "Liberia"),
(29, "AF", "LBY", "Libyan",                   "Libya"),
(30, "AF", "MDG", "Malagasy",                 "Madagascar"),
(31, "AF", "MWI", "Malawian",                 "Malawi"),
(32, "AF", "MLI", "Malian",                   "Mali"),
(33, "AF", "MRT", "Mauritanian",              "Mauritania"),
(34, "AF", "MUS", "Mauritius",                "Mauritius"),
(35, "AF", "MAR", "Moroccan",                 "Morocco"),
(36, "AF", "MOZ", "Mozambique",               "Mozambique"),
(37, "AF", "NAM", "Namibian",                 "Namibia"),
(38, "AF", "NER", "Niger",                    "Niger"),
(39, "AF", "NGA", "Nigerian",                 "Nigeria"),
(40, "AF", "RWA", "Rwandan",                  "Rwanda"),
(41, "AF", "STP", "Sao Tome and Principe",    "Sao Tome and Principe"),
(42, "AF", "SEN", "Senegalese",               "Senegal"),
(43, "AF", "SYC", "Seychellois",              "Seychelles"),
(44, "AF", "SLE", "Sierra Leonean",           "Sierra Leone"),
(45, "AF", "SOM", "Somali",                   "Somalia"),
(46, "AF", "ZAF", "South African",            "South Africa"),
(47, "AF", "SSD", "South Sudanese",           "South Sudan"),
(48, "AF", "SDN", "Sudanese",                 "Sudan"),
(49, "AF", "TZA", "Tanzanian",                "Tanzania"),
(50, "AF", "TGO", "Togolese",                 "Togo"),
(51, "AF", "TUN", "Tunisian",                 "Tunisia"),
(52, "AF", "UGA", "Ugandan",                  "Uganda"),
(53, "AF", "ZMB", "Zambian",                  "Zambia"),
(54, "AF", "ZWE", "Zimbabwean",               "Zimbabwe"),

(55, "AM", "USA", "American",               "United States of America"),
(56, "AM", "ATG", "Antigua and Barbuda",    "Antigua and Barbuda"),
(57, "AM", "ARG", "Argentine",              "Argentina"),
(58, "AM", "BHS", "Bahamian",               "Bahamas"),
(59, "AM", "BRB", "Bajan",                  "Barbados"),
(60, "AM", "BLZ", "Belizean",               "Belize"),
(61, "AM", "BOL", "Bolivian",               "Bolivia"),
(62, "AM", "BRA", "Brazilian",              "Brazil"),
(63, "AM", "CAN", "Canadian",               "Canada"),
(64, "AM", "CHL", "Chilean",                "Chile"),
(65, "AM", "COL", "Colombian",              "Colombia"),
(66, "AM", "CRI", "Costa Rican",            "Costa Rica"),
(67, "AM", "CUB", "Cuban",                  "Cuba"),
(68, "AM", "DMA", "Dominica",               "Dominica"),
(69, "AM", "DOM", "Dominican Republic",     "Dominican Republic"),
(70, "AM", "ECU", "Ecuadorian",             "Ecuador"),
(71, "AM", "GRD", "Grenada",                "Grenada"),
(72, "AM", "GTM", "Guatemalan",             "Guatemala"),
(73, "AM", "GUY", "Guyanese",               "Guyana"),
(74, "AM", "HTI", "Haitian",                "Haiti"),
(75, "AM", "HND", "Honduran",               "Honduras"),
(76, "AM", "JAM", "Jamaican",               "Jamaica"),
(77, "AM", "MEX", "Mexican",                "Mexico"),
(78, "AM", "NIC", "Nicaraguan",             "Nicaragua"),
(79, "AM", "PAN", "Panamanian",             "Panama"),
(80, "AM", "PRY", "Paraguayan",             "Paraguay"),
(81, "AM", "PER", "Peruvian",               "Peru"),
(82, "AM", "KNA", "Kittian Nevisian",       "Saint Kitts and Nevis"),
(83, "AM", "LCA", "Saint Lucian",           "Saint Lucia"),
(84, "AM", "VCT", "Vincentian Grenadinian", "Saint Vincent and the Grenadines"),
(85, "AM", "SLV", "Salvadoran",             "El Salvador"),
(86, "AM", "SUR", "Surinamese",             "Suriname"),
(87, "AM", "TTO", "Trinidad and Tobago",    "Trinidad and Tobago"),
(88, "AM", "URY", "Uruguayan",              "Uruguay"),
(89, "AM", "VEN", "Venezuelan",             "Venezuala"),

(90,  "AS", "AFG", "Afghan",        "Afghanistan"),
(91,  "AS", "ARM", "Armenian",      "Armenia"),
(92,  "AS", "AZE", "Azerbaijani",   "Azerbaijan"),
(93,  "AS", "BHR", "Bahraini",      "Bahrain"),
(94,  "AS", "BGD", "Bangladeshi",   "Bangladesh"),
(95,  "AS", "BTN", "Bhutanese",     "Bhutan"),
(96,  "AS", "BRN", "Bruneian",      "Brunei"),
(97,  "AS", "KHM", "Cambodian",     "Cambodia"),
(98,  "AS", "CHN", "Chinese",       "China"),
(99,  "AS", "CYP", "Cypriot",       "Cyprus"),
(100, "AS", "GEO", "Georgian",      "Georgia"),
(101, "AS", "IND", "Indian",        "India"),
(102, "AS", "IDN", "Indonesian",    "Indonesia"),
(103, "AS", "IRN", "Iranian",       "Iran"),
(104, "AS", "IRQ", "Iraqi",         "Iraq"),
(105, "AS", "ISR", "Israeli",       "Israel"),
(106, "AS", "JPN", "Japanese",      "Japan"),
(107, "AS", "JOR", "Jordanian",     "Jordan"),
(108, "AS", "KAZ", "Kazakh",        "Kazakhstan"),
(109, "AS", "KWT", "Kuwaiti",       "Kuwait"),
(110, "AS", "KGZ", "Kyrgyz",        "Kyrgyzstan"),
(111, "AS", "LAO", "Lao",           "Laos"),
(112, "AS", "LBN", "Lebanese",      "Lebanon"),
(113, "AS", "MYS", "Malaysian",     "Malaysia"),
(114, "AS", "MDV", "Maldivian",     "Maldives"),
(115, "AS", "MNG", "Mongolian",     "Mongolia"),
(116, "AS", "MMR", "Burmese",       "Myanmar"),
(117, "AS", "NPL", "Nepalese",      "Nepal"),
(118, "AS", "PRK", "North Korean",  "North Korea"),
(119, "AS", "OMN", "Omani",         "Oman"),
(120, "AS", "PAK", "Pakistani",     "Pakistan"),
(121, "AS", "PSE", "Palestinian",   "Palestine"),
(122, "AS", "PHL", "Filipino",      "Philippines"),
(123, "AS", "QAT", "Qatari",        "Qatar"),
(124, "AS", "RUS", "Russian",       "Russia"),
(125, "AS", "SAU", "Saudi Arabian", "Saudi Arabia"),
(126, "AS", "SGP", "Singaporean",   "Singapore"),
(127, "AS", "KOR", "South Korean",  "South Korea"),
(128, "AS", "LKA", "Sri Lankan",    "Sri Lanka"),
(129, "AS", "SYR", "Syrian",        "Syria"),
(130, "AS", "TWN", "Taiwanese",     "Taiwan"),
(131, "AS", "TJK", "Tajik",         "Tajikistan"),
(132, "AS", "THA", "Thai",          "Thailand"),
(133, "AS", "TLS", "Timorese",      "Timor-Leste"),
(134, "AS", "TUR", "Turkish",       "Turkey"),
(135, "AS", "TKM", "Turkmen",       "Turkmenistan"),
(136, "AS", "ARE", "Emirati",       "United Arab Emirates"),
(137, "AS", "UZB", "Uzbek",         "Uzbekistan"),
(138, "AS", "VNM", "Vietnamese",    "Vietnam"),
(139, "AS", "YEM", "Yemeni",        "Yemen"),

(140, "EU", "ALB", "Albanian",               "Albania"),
(141, "EU", "AND", "Catalan",                "Andorra"),
(142, "EU", "AUT", "Austrian",               "Austria"),
(143, "EU", "BLR", "Belarusian",             "Belarus"),
(144, "EU", "BEL", "Belgian",                "Belgium"),
(145, "EU", "BIH", "Bosnia and Herzegovina", "Bosnia and Herzegovina"),
(146, "EU", "BGR", "Bulgarian",              "Bulgaria"),
(147, "EU", "HRV", "Croatian",               "Croatia"),
(148, "EU", "CZE", "Czech",                  "Czechia"),
(149, "EU", "DNK", "Danish",                 "Denmark"),
(150, "EU", "EST", "Estonian",               "Estonia"),
(151, "EU", "FIN", "Finnish",                "Finland"),
(152, "EU", "FRA", "French",                 "France"),
(153, "EU", "DEU", "German",                 "Germany"),
(154, "EU", "GRC", "Greek",                  "Greece"),
(155, "EU", "HUN", "Hungarian",              "Hungary"),
(156, "EU", "ISL", "Icelandic",              "Iceland"),
(157, "EU", "IRL", "Irish",                  "Ireland"),
(158, "EU", "ITA", "Italian",                "Italy"),
(160, "EU", "XXK", "Kosovan",                "Kosovo"),
(161, "EU", "LVA", "Latvian",                "Latvia"),
(162, "EU", "LIE", "Liechtensteiner",        "Liechtenstein"),
(163, "EU", "LTU", "Lithuanian",             "Lithuania"),
(164, "EU", "LUX", "Luxembourg",             "Luxembourg"),
(165, "EU", "MLT", "Maltese",                "Malta"),
(166, "EU", "MDA", "Moldovan",               "Moldova"),
(167, "EU", "MCO", "Monégasque",             "Monaco"),
(168, "EU", "MNE", "Montenegrin",            "Montenegro"),
(169, "EU", "NLD", "Dutch",                  "Netherlands"),
(170, "EU", "MKD", "Macedonian",             "North Macedonia"),
(171, "EU", "NOR", "Norwegian",              "Norway"),
(172, "EU", "POL", "Polish",                 "Poland"),
(173, "EU", "PRT", "Portuguese",             "Portugal"),
(174, "EU", "ROU", "Romanian",               "Romania"),
(175, "EU", "SMR", "Sammarinese",            "San Marino"),
(176, "EU", "SRB", "Serbian",                "Serbia"),
(177, "EU", "SVK", "Slovak",                 "Slovakia"),
(178, "EU", "SVN", "Slovenian",              "Slovenia"),
(179, "EU", "ESP", "Spanish",                "Spain"),
(180, "EU", "SWE", "Swedish",                "Sweden"),
(181, "EU", "CHE", "Swiss",                  "Switzerland"),
(182, "EU", "UKR", "Ukrainian",              "Ukraine"),
(183, "EU", "GBR", "British",                "United Kingdom"),

(184, "OC", "AUS", "Australian",        "Australia"),
(185, "OC", "FJI", "Fijian",            "Fiji"),
(186, "OC", "KIR", "Kiribati",          "Kiribati"),
(187, "OC", "MHL", "Marshallese",       "Marshall Islands"),
(188, "OC", "FSM", "Micronesian",       "Micronesia"),
(189, "OC", "NRU", "Nauruan",           "Nauru"),
(190, "OC", "NZL", "New Zealand",       "New Zealand"),
(191, "OC", "PLW", "Palauan",           "Palau"),
(192, "OC", "PNG", "Papua New Guinean", "Papua New Guinea"),
(193, "OC", "WSM", "Samoan",            "Samoa"),
(194, "OC", "SLB", "Solomon Islander",  "Solomon Islands"),
(195, "OC", "TON", "Tongan",            "Tonga"),
(196, "OC", "TUV", "Tuvaluan",          "Tuvalu"),
(197, "OC", "VUT", "Vanuatuan",         "Vanuatu");

INSERT INTO equipment
(equipment_type_id, author_id, owner_id, name, description, image)
VALUES
(2, 1, 1, "Ceramic Stone",                    "It works.", "ceramic-stone"),
(2, 1, 1, "Chef\'s Knife",                    "It works.", "chefs-knife"),
(2, 1, 1, "Cutting Board",                    "It works.", "cutting-board"),
(2, 1, 1, "Y Peeler",                         "It works.", "y-peeler"),
(3, 1, 1, "Wooden Spoon",                     "It works.", "wooden-spoon"),
(2, 1, 1, "Serated Knife",                    "It works.", "serated-knife"),
(2, 1, 1, "Rubber Spatula",                   "It works.", "rubber-spatula"),
(2, 1, 1, "Whisk",                            "It works.", "whisk"),
(2, 1, 1, "Pepper Mill",                      "It works.", "pepper-mill"),
(2, 1, 1, "Can Opener",                       "It works.", "can-opener"),
(2, 1, 1, "Side Peeler",                      "It works.", "side-peeler"),
(2, 1, 1, "Box Grater",                       "It works.", "box-grater"),
(2, 1, 1, "Small Mixing Bowl",                "It works.", "small-mixing-bowl"),
(2, 1, 1, "Medium Mixing Bowl",               "It works.", "medium-mixing-bowl"),
(2, 1, 1, "Large Mixing Bowl",                "It works.", "large-mixing-bowl"),
(2, 1, 1, "Salad Spinner",                    "It works.", "salad-spinner"),
(2, 1, 1, "Dry Measuring Cups",               "It works.", "dry-measuring-cups"),
(2, 1, 1, "Liquid Measuring Cups",            "It works.", "liquid-measuring-cups"),
(2, 1, 1, "Measuring Spoons",                 "It works.", "measuring-spoons"),
(2, 1, 1, "Measuring Pitcher",                "It works.", "measuring-pitcher"),
(2, 1, 1, "Digital Scale",                    "It works.", "digital-scale"),
(2, 1, 1, "Handheld Mixer",                   "It works.", "handheld-mixer"),
(2, 1, 1, "Blender",                          "It works.", "blender"),
(2, 1, 1, "Immersion Blender",                "It works.", "immersion-blender"),
(2, 1, 1, "Parchment Paper",                  "It works.", "parchment-paper"),
(2, 1, 1, "Plastic Wrap",                     "It works.", "plastic-wrap"),
(2, 1, 1, "Aluminum Foil",                    "It works.", "aluminum-foil"),
(2, 1, 1, "Cheesecloth",                      "It works.", "cheesecloth"),

(3, 1, 1, "Coffee Maker",                     "It works.", "coffee-maker"),
(3, 1, 1, "Tea Pot",                          "It works.", "tea-pot"),
(3, 1, 1, "Microwave",                        "It works.", "ladle"),
(3, 1, 1, "Toaster Oven",                     "It works.", "ladle"),
(3, 1, 1, "Small Sauce Pan",                  "It works.", "small-sauce-pan"),
(3, 1, 1, "Medium Sauce Pan",                 "It works.", "medium-sauce-pan"),
(3, 1, 1, "Medium Stock Pot",                 "It works.", "medium-stock-pot"),
(3, 1, 1, "Large Stock Pot",                  "It works.", "large-stock-pot"),
(3, 1, 1, "Stainless Steel Lidded Saute Pan", "It works.", "stainless-steel-lidded-saute-pan"),
(3, 1, 1, "Small Stainless Steel Skillet",    "It works.", "small-stainless-steel-skillet"),
(3, 1, 1, "Large Stainless Steel Skillet",    "It works.", "large-stainless-steel-skillet"),
(3, 1, 1, "Small Cast-Iron Skillet",          "It works.", "small-cast-iron-skillet"),
(3, 1, 1, "Large Cast-Iron Skillet",          "It works.", "large-cast-iron-skillet"),
(3, 1, 1, "Glass Baking Dish",                "It works.", "glass-baking-dish"),
(3, 1, 1, "Sturdy Baking Sheet",              "It works.", "sturdy-baking-dish"),
(3, 1, 1, "Small Gratin Dish",                "It works.", "small-gratin-dish"),
(3, 1, 1, "Large Gratin Dish",                "It works.", "large-gratin-dish"),
(3, 1, 1, "Dutch Oven",                       "It works.", "dutch-oven"),
(3, 1, 1, "Oven Mitts",                       "It works.", "oven-mitts"),
(3, 1, 1, "Splatter Screen",                  "It works.", "splatter-screen"),
(3, 1, 1, "Colander",                         "It works.", "colander"),
(3, 1, 1, "Mesh Strainer",                    "It works.", "mesh-strainer"),
(3, 1, 1, "Tongs",                            "It works.", "tongs"),
(3, 1, 1, "Slotted Spoon",                    "It works.", "slotted-spoon"),
(3, 1, 1, "Serving Spoon",                    "It works.", "serving-spoon"),
(3, 1, 1, "Spider",                           "It works.", "spider"),
(3, 1, 1, "Sturdy Spatula",                   "It works.", "sturdy-spatula"),
(3, 1, 1, "Fish Spatula",                     "It works.", "fish-spatula"),
(3, 1, 1, "Ladle",                            "It works.", "ladle");

INSERT INTO ingredients
(ingredient_type_id, author_id, owner_id, variety, name, description, image)
VALUES
(1, 1, 1, "",                    "Tuna",                                     "Tasty.", "tuna"),
(1, 1, 1, "",                    "Salmon",                                   "Tasty.", "salmon"),
(1, 1, 1, "",                    "Tilapia",                                  "Tasty.", "tilapia"),
(1, 1, 1, "",                    "Pollock",                                  "Tasty.", "pollock"),
(1, 1, 1, "",                    "Catfish",                                  "Tasty.", "catfish"),
(1, 1, 1, "",                    "Cod",                                      "Tasty.", "cod"),

(2, 1, 1, "",                    "Clams",                                    "Tasty.", "clams"),
(2, 1, 1, "",                    "Crab",                                     "Tasty.", "crab"),
(2, 1, 1, "",                    "Shrimp",                                   "Tasty.", "shrimp"),

(3, 1, 1, "",                    "Chuck Seven Bone Roast",                   "Tasty.", "chuck-7-bone-roast"),
(3, 1, 1, "",                    "Chuck Seven Bone Steak",                   "Tasty.", "chuck-7-bone-steak"),
(3, 1, 1, "",                    "Chuck Arm Roast",                          "Tasty.", "chuck-arm-roast"),
(3, 1, 1, "Boneless",            "Chuck Arm Roast",                          "Tasty.", "chuck-arm-rost-boneless"),
(3, 1, 1, "",                    "Chuck Arm Steak",                          "Tasty.", "chuck-arm-steak"),
(3, 1, 1, "Boneless",            "Chuck Arm Steak",                          "Tasty.", "chuck-arm-steak-boneless"),
(3, 1, 1, "",                    "Chuck Blade Roast",                        "Tasty.", "chuck-blade-roast"),
(3, 1, 1, "",                    "Chuck Blade Steak",                        "Tasty.", "chuck-blade-steak"),
(3, 1, 1, "Boneless",            "Chuck Blade Steak",                        "Tasty.", "chuck-blade-steak-boneless"),
(3, 1, 1, "Cap Off",             "Chuck Blade Steak",                        "Tasty.", "chuck-blade-steak-cap-off"),
(3, 1, 1, "",                    "Chuck Cross Rib Roast",                    "Tasty.", "chuck-cross-rib-roast"),
(3, 1, 1, "Boneless",            "Chuck Cross Rib Roast",                    "Tasty.", "chuck-cross-rib-roast-boneless"),
(3, 1, 1, "",                    "Chuck Eye Edge Roast",                     "Tasty.", "chuck-eye-edge-roast"),
(3, 1, 1, "Boneless",            "Chuck Eye Roast",                          "Tasty.", "chuck-eye-roast-steak"),
(3, 1, 1, "Boneless",            "Chuck Eye Steak",                          "Tasty.", "chuck-eye-steak-boneless"),
(3, 1, 1, "",                    "Chuck Flanken Style Ribs",                 "Tasty.", "chuck-flanken-style-ribs"),
(3, 1, 1, "Boneless",            "Chuck Flanken Style Ribs",                 "Tasty.", "chuck-flanken-style-ribs-boneless"),
(3, 1, 1, "",                    "Chuck Flat Ribs",                          "Tasty.", "chuck-flat-ribs"),
(3, 1, 1, "",                    "Chuck Mock Tender Roast",                  "Tasty.", "chuck-mock-tender-roast"),
(3, 1, 1, "",                    "Chuck Mock Tender Steak",                  "Tasty.", "chuck-mock-tender-steak"),
(3, 1, 1, "",                    "Chuck Neck Roast",                         "Tasty.", "chuck-neck-roast"),
(3, 1, 1, "Boneless",            "Chuck Neck Roast",                         "Tasty.", "chuck-neck-roast-boneless"),
(3, 1, 1, "Boneless",            "Chuck Roast",                              "Tasty.", "chuck-roast-boneless"),
(3, 1, 1, "",                    "Chuck Short Ribs",                         "Tasty.", "chuck-short-ribs"),
(3, 1, 1, "Boneless",            "Chuck Short Ribs",                         "Tasty.", "chuck-short-ribs-boneless"),
(3, 1, 1, "",                    "Chuck Shoulder Center Steak Ranch Steak",  "Tasty.", "chuck-shoulder-center-steak-ranch-steak"),
(3, 1, 1, "",                    "Chuck Shoulder Roast",                     "Tasty.", "chuck-shoulder-roast"),
(3, 1, 1, "Boneless",            "Chuck Shoulder Roast",                     "Tasty.", "chuck-shoulder-roast-boneless"),
(3, 1, 1, "Boneless",            "Chuck Shoulder Steak",                     "Tasty.", "chuck-shoulder-steak-boneless"),
(3, 1, 1, "",                    "Chuck Shoulder Tender",                    "Tasty.", "chuck-shoulder-tender"),
(3, 1, 1, "",                    "Chuck Shoulder Tender Medallions",         "Tasty.", "chuck-shoulder-tender-medallions"),
(3, 1, 1, "Boneless",            "Chuck Shoulder Top Blade Roast",           "Tasty.", "chuck-shoulder-top-blade-roast-boneless"),
(3, 1, 1, "Boneless",            "Chuck Shoulder Top Blade Steak",           "Tasty.", "chuck-shoulder-top-blade-steak-boneless"),
(3, 1, 1, "",                    "Chuck Shoulder Top Blade Steak Flat Iron", "Tasty.", "chuck-shoulder-top-blade-steak-flat-iron"),
(3, 1, 1, "",                    "Chuck Top Blade Roast",                    "Tasty.", "chuck-top-blade-roast"),
(3, 1, 1, "Bone In",             "Chuck Top Blade Steak",                    "Tasty.", "chuck-top-blade-steak-bone-in"),
(3, 1, 1, "",                    "Chuck Under Blade Roast",                  "Tasty.", "chuck-under-blade-roast"),
(3, 1, 1, "Boneless",            "Chuck Under Blade Roast",                  "Tasty.", "chuck-under-blade-roast-boneless"),
(3, 1, 1, "",                    "Chuck Under Blade Steak",                  "Tasty.", "chuck-under-blade-steak"),
(3, 1, 1, "Boneless",            "Chuck Under Blade Steak",                  "Tasty.", "chuck-under-blade-steak-boneless"),
(3, 1, 1, "",                    "Round Bottom Round Roast",                 "Tasty.", "round-bottom-round-roast"),
(3, 1, 1, "",                    "Round Bottom Round Roast Triangle Roast",  "Tasty.", "round-bottom-round-roast-triangle-roast"),
(3, 1, 1, "",                    "Round Bottom Round Rump Roast",            "Tasty.", "round-bottom-round-rump-roast"),
(3, 1, 1, "",                    "Round Bottom Round Steak",                 "Tasty.", "round-bottom-round-steak"),
(3, 1, 1, "",                    "Round Bottom Round Steak Western Griller", "Tasty.", "round-bottom-round-steak-western-griller"),
(3, 1, 1, "",                    "Round Eye Round Roast",                    "Tasty.", "round-eye-round-roast"),
(3, 1, 1, "",                    "Round Eye Round Steak",                    "Tasty.", "round-eye-round-steak"),
(3, 1, 1, "",                    "Round Heel of Round",                      "Tasty.", "round-heel-of-round"),
(3, 1, 1, "",                    "Round Sirloin Tip Center Roast",           "Tasty.", "round-sirloin-tip-center-roast"),
(3, 1, 1, "",                    "Round Sirloin Tip Center Steak",           "Tasty.", "round-sirloin-tip-center-steak"),
(3, 1, 1, "",                    "Round Sirloin Tip Side Steak",             "Tasty.", "round-sirloin-tip-side-steak"),
(3, 1, 1, "",                    "Round Steak",                              "Tasty.", "round-steak"),
(3, 1, 1, "Boneless",            "Round Steak",                              "Tasty.", "round-steak-boneless"),
(3, 1, 1, "",                    "Round Tip Roast",                          "Tasty.", "round-tip-roast"),
(3, 1, 1, "Cap Off",             "Round Tip Roast",                          "Tasty.", "round-tip-roast-cap-off"),
(3, 1, 1, "",                    "Round Tip Steak",                          "Tasty.", "round-tip-steak"),
(3, 1, 1, "Cap Off",             "Round Tip Steak",                          "Tasty.", "round-tip-steak-cap-off"),
(3, 1, 1, "",                    "Round Top Round Roast",                    "Tasty.", "round-top-round-roast"),
(3, 1, 1, "Cap Off",             "Round Top Round Roast",                    "Tasty.", "round-top-round-roast-cap-off"),
(3, 1, 1, "",                    "Round Top Round Steak",                    "Tasty.", "round-top-round-steak"),
(3, 1, 1, "",                    "Round Top Round Steak Butterflied",        "Tasty.", "round-top-round-steak-butterflied"),
(3, 1, 1, "",                    "Round Top Round Steak First Cut",          "Tasty.", "round-top-round-steak-first-cut"),
(3, 1, 1, "",                    "Loin Ball Tip Roast",                      "Tasty.", "loin-ball-tip-roast"),
(3, 1, 1, "",                    "Loin Ball Tip Steak",                      "Tasty.", "loin-ball-tip-steak"),
(3, 1, 1, "",                    "Loin Flap Meat Steak",                     "Tasty.", "loin-flap-meat-steak"),
(3, 1, 1, "",                    "Loin Porterhouse Steak",                   "Tasty.", "loin-porterhouse-steak"),
(3, 1, 1, "",                    "Loin Shell Sirloin Steak",                 "Tasty.", "loin-shell-sirloin-steak"),
(3, 1, 1, "",                    "Loin Sirloin Steak",                       "Tasty.", "loin-sirloin-steak"),
(3, 1, 1, "",                    "Loin T Bone Steak",                        "Tasty.", "loin-t-bone-steak"),
(3, 1, 1, "",                    "Loin Tenderloin Roast",                    "Tasty.", "loin-tenderloin-roast"),
(3, 1, 1, "",                    "Loin Tenderloin Steak",                    "Tasty.", "loin-tenderloin-steak"),
(3, 1, 1, "",                    "Loin Top Loin Roast",                      "Tasty.", "loin-top-loin-roast"),
(3, 1, 1, "Boneless",            "Loin Top Loin Roast",                      "Tasty.", "loin-top-loin-roast-boneless"),
(3, 1, 1, "",                    "Loin Top Loin Steak",                      "Tasty.", "loin-top-loin-steak"),
(3, 1, 1, "Boneless",            "Loin Top Loin Steak",                      "Tasty.", "loin-top-loin-steak-boneless"),
(3, 1, 1, "Boneless",            "Loin Top Sirloin Roast",                   "Tasty.", "loin-top-sirloin-roast-boneless"),
(3, 1, 1, "Boneless Cap Off",    "Loin Top Sirloin Roast",                   "Tasty.", "loin-top-sirloin-roast-boneless-cap-off"),
(3, 1, 1, "Boneless",            "Loin Top Sirloin Steak",                   "Tasty.", "loin-top-sirloin-steak-boneless"),
(3, 1, 1, "Boneless Cap Off",    "Loin Top Sirloin Steak",                   "Tasty.", "loin-top-sirloin-steak-boneless-cap-off"),
(3, 1, 1, "",                    "Loin Tri Tip Roast",                       "Tasty.", "loin-tri-tip-roast"),
(3, 1, 1, "",                    "Loin Tri Tip Steak",                       "Tasty.", "loin-tri-tip-steak"),
(3, 1, 1, "",                    "Shank Cross Cut",                          "Tasty.", "shank-cross-cut"),
(3, 1, 1, "Boneless",            "Shank Cross Cut",                          "Tasty.", "shank-cross-cut-boneless"),
(3, 1, 1, "",                    "Plate Skirt Steak",                        "Tasty.", "plate-skirt-steak"),
(3, 1, 1, "",                    "Flank Steak",                              "Tasty.", "flank-flank-steak"),
(3, 1, 1, "",                    "Ground Beef",                              "Tasty.", "ground-beef"),
(3, 1, 1, "",                    "Back Ribs",                                "Tasty.", "back-ribs"),
(3, 1, 1, "Boneless",            "Rib Cap Meat",                             "Tasty.", "rib-cap-meat-boneless"),
(3, 1, 1, "",                    "Rib Extra Trim Roast Large End",           "Tasty.", "rib-extra-trim-roast-large-end"),
(3, 1, 1, "",                    "Ribeye Roast",                             "Tasty.", "ribeye-roast"),
(3, 1, 1, "Lip On Bone In",      "Ribeye Roast",                             "Tasty.", "ribeye-roast-lip-on-bone-in"),
(3, 1, 1, "Lip On Boneless",     "Ribeye Roast",                             "Tasty.", "ribeye-roast-lip-on-boneless"),
(3, 1, 1, "",                    "Ribeye Steak",                             "Tasty.", "ribeye-steak"),
(3, 1, 1, "Lip On Bone In",      "Ribeye Steak",                             "Tasty.", "ribeye-steak-lip-on-bone-in"),
(3, 1, 1, "Lip On Boneless",     "Ribeye Steak",                             "Tasty.", "ribeye-steak-lip-on-boneless"),
(3, 1, 1, "",                    "Rib Roast Large End",                      "Tasty.", "rib-roast-large-end"),
(3, 1, 1, "Boneless",            "Rib Roast Large End",                      "Tasty.", "rib-roast-large-end-boneless"),
(3, 1, 1, "",                    "Rib Roast Small End",                      "Tasty.", "rib-roast-small-end"),
(3, 1, 1, "Boneless",            "Rib Roast Small End",                      "Tasty.", "rib-roast-small-end-boneless"),
(3, 1, 1, "Boneless",            "Rib Rolled Cap Pot Roast",                 "Tasty.", "rib-rolled-cap-pot-roast-boneless"),
(3, 1, 1, "",                    "Rib Short Ribs",                           "Tasty.", "rib-short-ribs"),
(3, 1, 1, "Boneless",            "Rib Short Ribs",                           "Tasty.", "rib-short-ribs-boneless"),
(3, 1, 1, "",                    "Rib Steak Large End",                      "Tasty.", "rib-steak-large-end"),
(3, 1, 1, "",                    "Rib Steak Small End",                      "Tasty.", "rib-steak-small-end"),
(3, 1, 1, "Boneless",            "Rib Steak Small End",                      "Tasty.", "rib-steak-small-end-boneless"),

(4, 1, 1, "",                    "Bacon",                                    "Tasty.", "bacon"),

(5, 1, 1, "Bone In",             "Chicken Breasts",                          "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "Boneless",            "Chicken Breasts",                          "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "",                    "Chicken Breasts",                          "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "",                    "Chicken Tenderloins",                      "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "Bone In",             "Chicken Thighs",                           "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "Boneless",            "Chicken Thighs",                           "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "",                    "Chicken Thighs",                           "Tasty.", "raw-chicken-wings"),
(5, 1, 1, "",                    "Chicken Wings",                            "Tasty.", "raw-chicken-wings"),

(6, 1, 1, "",                    "Extra Large Eggs",                         "Tasty.", "eggs"),
(6, 1, 1, "",                    "Large Eggs",                               "Tasty.", "eggs"),
(6, 1, 1, "",                    "Medium Eggs",                              "Tasty.", "eggs"),

(7, 1, 1, "Salted",              "Butter",                                   "Tasty.", "butter"),
(7, 1, 1, "Unsalted",            "Butter",                                   "Tasty.", "butter"),
(7, 1, 1, "",                    "Cream",                                    "Tasty.", "cream"),

(8, 1, 1, "",                    "Coconut",                                  "Tasty.", "coconut"),

(9, 1, 1, "Corn",                "Starch",                                   "Tasty.", "eggs"),
(9, 1, 1, "Potato",              "Starch",                                   "Tasty.", "eggs"),
(9, 1, 1, "All-Purpose",         "Flour",                                    "Tasty.", "eggs"),

(10, 1, 1, "Black Turtle",       "Beans",                                    "Tasty.", "black-turtle-beans"),
(10, 1, 1, "Garbanzo",           "Beans",                                    "Tasty.", "garbanzo-beans-chickpeas"),
(10, 1, 1, "Great Northern",     "Beans",                                    "Tasty.", "great-northern-beans"),
(10, 1, 1, "Pinto",              "Beans",                                    "Tasty.", "pinto-beans"),
(10, 1, 1, "Red Kidney",         "Beans",                                    "Tasty.", "red-kidney-beans"),
(10, 1, 1, "",                   "Split Peas",                               "Tasty.", "split-peas"),

(11, 1, 1, "All Blue",           "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Austrian Crescent",  "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "French Fingerling",  "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Kennebec",           "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "LaRette",            "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Norland Red",        "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Purple Majesty",     "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Red Gold",           "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Red Thumb",          "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Russet Ranger",      "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Russet Burbank",     "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Russet Norkotah",    "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Russet Umatilla",    "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Russian Banana",     "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "Yukon Gold",         "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "",                   "Potatoes",                                 "Tasty.", "potatoes"),
(11, 1, 1, "",                   "Broccoli",                                 "Tasty.", "broccoli"),
(11, 1, 1, "",                   "Brussels Sprouts",                         "Tasty.", "brussels-sprouts"),
(11, 1, 1, "",                   "Bok Choy",                                 "Tasty.", "bok-choy"),
(11, 1, 1, "Green",              "Cabbage",                                  "Tasty.", "green-cabbage"),
(11, 1, 1, "Red",                "Cabbage",                                  "Tasty.", "red-cabbage"),
(11, 1, 1, "Napa",               "Cabbage",                                  "Tasty.", "napa-cabbage-chinese-cabbage"),
(11, 1, 1, "Savoy",              "Cabbage",                                  "Tasty.", "savoy-cabbage"),
(11, 1, 1, "",                   "Cauliflower",                              "Tasty.", "cauliflower"),
(11, 1, 1, "",                   "Kohlrabi",                                 "Tasty.", "kohlrabi"),
(11, 1, 1, "",                   "Collard Greens",                           "Tasty.", "collard-greens"),
(11, 1, 1, "",                   "Turnip Greens",                            "Tasty.", "turnip-greens"),
(11, 1, 1, "",                   "Pak Choy Baby Bok Choy",                   "Tasty.", "pak-choy-baby-bok-choy"),
(11, 1, 1, "",                   "Zucchini",                                 "Tasty.", "zucchini"),
(11, 1, 1, "Standard Slicing",   "Cucumber",                                 "Tasty.", "standard-slicing-cucumber"),
(11, 1, 1, "Purple",             "Eggplant",                                 "Tasty.", "purple-eggplant"),
(11, 1, 1, "White",              "Eggplant",                                 "Tasty.", "white-eggplant"),
(11, 1, 1, "Japanese",           "Eggplant",                                 "Tasty.", "japanese-eggplant"),
(11, 1, 1, "",                   "Pumpkin",                                  "Tasty.", "pumpkin"),
(11, 1, 1, "Acorn",              "Squash",                                   "Tasty.", "acorn-squash"),
(11, 1, 1, "Butternut",          "Squash",                                   "Tasty.", "butternut-squash"),
(11, 1, 1, "Hubbard",            "Squash",                                   "Tasty.", "hubbard-squash"),
(11, 1, 1, "Spaghetti",          "Squash",                                   "Tasty.", "spaghetti-squash"),
(11, 1, 1, "Delicata",           "Squash",                                   "Tasty.", "delicata-squash"),
(11, 1, 1, "Boston",             "Lettuce",                                  "Tasty.", "boston-lettuce"),
(11, 1, 1, "Bibb",               "Lettuce",                                  "Tasty.", "bibb-lettuce"),
(11, 1, 1, "Iceberg",            "Lettuce",                                  "Tasty.", "iceberg-lettuce"),
(11, 1, 1, "Romaine",            "Lettuce",                                  "Tasty.", "romaine-lettuce"),
(11, 1, 1, "Green Leaf",         "Lettuce",                                  "Tasty.", "green-leaf-lettuce"),
(11, 1, 1, "Oak Leaf",           "Lettuce",                                  "Tasty.", "oak-leaf-lettuce"),
(11, 1, 1, "Red Leaf",           "Lettuce",                                  "Tasty.", "red-leaf-lettuce"),
(11, 1, 1, "",                   "Arugula Rocket",                           "Tasty.", "arugula-rocket"),
(11, 1, 1, "",                   "Belgian Endive",                           "Tasty.", "belgian-endive"),
(11, 1, 1, "",                   "Frisee",                                   "Tasty.", "frisee"),
(11, 1, 1, "",                   "Escarole",                                 "Tasty.", "escarole"),
(11, 1, 1, "",                   "Mache Lambs Lettuce",                      "Tasty.", "mache-lambs-lettuce"),
(11, 1, 1, "",                   "Radicchio",                                "Tasty.", "radicchio"),
(11, 1, 1, "",                   "Watercress",                               "Tasty.", "watercress"),
(11, 1, 1, "Baby",               "Spinach",                                  "Tasty.", "baby-spinach"),
(11, 1, 1, "Frozen",             "Spinach",                                  "Tasty.", "spinach"),
(11, 1, 1, "",                   "Spinach",                                  "Tasty.", "spinach"),
(11, 1, 1, "",                   "Swiss Chard",                              "Tasty.", "swiss-chard"),
(11, 1, 1, "",                   "Beet Greens",                              "Tasty.", "beet-greens"),
(11, 1, 1, "",                   "Dandelion Greens",                         "Tasty.", "dandelion-greens"),
(11, 1, 1, "",                   "Mustard Greens",                           "Tasty.", "mustard-greens"),
(11, 1, 1, "Shiitake",           "Mushrooms",                                "Tasty.", "shiitake-mushrooms"),
(11, 1, 1, "Cremini",            "Mushrooms",                                "Tasty.", "cremini-mushrooms"),
(11, 1, 1, "Portobello",         "Mushrooms",                                "Tasty.", "portobello-mushrooms"),
(11, 1, 1, "",                   "Mushrooms",                                "Tasty.", "mushrooms"),
(11, 1, 1, "Globe",              "Onion",                                    "Tasty.", "globe-onion"),
(11, 1, 1, "Green",              "Onion",                                    "Tasty.", "scallion-green-onion"),
(11, 1, 1, "Spanish",            "Onion",                                    "Tasty.", "spanish-onion"),
(11, 1, 1, "Sweet",              "Onion",                                    "Tasty.", "sweet-onion"),
(11, 1, 1, "",                   "Onion",                                    "Tasty.", "onion"),
(11, 1, 1, "Pearl",              "Onions",                                   "Tasty.", "pearl-onions"),
(11, 1, 1, "",                   "Garlic",                                   "Tasty.", "garlic"),
(11, 1, 1, "",                   "Shallots",                                 "Tasty.", "shallots"),
(11, 1, 1, "",                   "Leek",                                     "Tasty.", "leek"),
(11, 1, 1, "Bell",               "Pepper",                                   "Tasty.", "bell-pepper"),
(11, 1, 1, "Poblano",            "Pepper",                                   "Tasty.", "poblano-pepper"),
(11, 1, 1, "Jalapeno",           "Pepper",                                   "Tasty.", "jalapeno-pepper"),
(11, 1, 1, "Serrano",            "Pepper",                                   "Tasty.", "serrano-pepper"),
(11, 1, 1, "Thai",               "Pepper",                                   "Tasty.", "thai-pepper"),
(11, 1, 1, "Habanero",           "Pepper",                                   "Tasty.", "habanero-pepper"),
(11, 1, 1, "Winterbor",          "Kale",                                     "Tasty.", "winterbor-kale-curly-kale"),
(11, 1, 1, "Red Russian",        "Kale",                                     "Tasty.", "red-russian-kale"),
(11, 1, 1, "",                   "Kale",                                     "Tasty.", "kale"),
(11, 1, 1, "",                   "Green Beans",                              "Tasty.", "green-beans"),
(11, 1, 1, "",                   "Celery",                                   "Tasty.", "celery"),
(11, 1, 1, "",                   "Asparagus",                                "Tasty.", "asparagus"),
(11, 1, 1, "Green",              "Peas",                                     "Tasty.", "green-peas"),
(11, 1, 1, "Snow",               "Peas",                                     "Tasty.", "snowpeas"),
(11, 1, 1, "Sugar Snap",         "Peas",                                     "Tasty.", "sugar-snap-peas"),
(11, 1, 1, "",                   "Carrots",                                  "Tasty.", "carrots"),
(11, 1, 1, "",                   "Parsnips",                                 "Tasty.", "parsnips"),
(11, 1, 1, "White",              "Turnips",                                  "Tasty.", "white-turnips"),
(11, 1, 1, "",                   "Turnips",                                  "Tasty.", "turnips"),
(11, 1, 1, "French",             "Radishes",                                 "Tasty.", "french-radishes"),
(11, 1, 1, "",                   "Radishes",                                 "Tasty.", "radishes"),
(11, 1, 1, "Baby Gold",          "Beets",                                    "Tasty.", "baby-gold-beets"),
(11, 1, 1, "Red",                "Beets",                                    "Tasty.", "red-beets"),
(11, 1, 1, "",                   "Beets",                                    "Tasty.", "beets"),
(11, 1, 1, "",                   "Daikon",                                   "Tasty.", "daikon"),
(11, 1, 1, "",                   "Horseradish",                              "Tasty.", "horseradish"),
(11, 1, 1, "",                   "Rutabaga",                                 "Tasty.", "rutabaga"),
(11, 1, 1, "",                   "Ginger",                                   "Tasty.", "ginger"),
(11, 1, 1, "",                   "Sunchoke Jerusalem Artichoke",             "Tasty.", "sunchoke-jerusalem-artichoke"),
(11, 1, 1, "",                   "Fennel",                                   "Tasty.", "fennel"),
(11, 1, 1, "",                   "Tomatillo",                                "Tasty.", "tomatillo"),
(11, 1, 1, "Standard Beefsteak", "Tomatoes",                                 "Tasty.", "standard-beefsteak-tomatoes"),
(11, 1, 1, "Plum Roma",          "Tomatoes",                                 "Tasty.", "plum-roma-san-marzano-tomatoes"),
(11, 1, 1, "Plum San Marzano",   "Tomatoes",                                 "Tasty.", "plum-roma-san-marzano-tomatoes"),
(11, 1, 1, "Sungold",            "Tomatoes",                                 "Tasty.", "cherry-tomatoes"),
(11, 1, 1, "Cherry",             "Tomatoes",                                 "Tasty.", "cherry-tomatoes"),
(11, 1, 1, "Grape",              "Tomatoes",                                 "Tasty.", "grape-tomatoes"),
(11, 1, 1, "",                   "Tomatoes",                                 "Tasty.", "cherry-tomatoes"),

(12, 1, 1, "Ambrosia",           "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Baldwin",            "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Braeburn",           "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Cameo",              "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Cortland",           "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Cosmic Crisp",       "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Empire",             "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Enterprise",         "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Fuji",               "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Gala",               "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Golden Delicious",   "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Granny Smith",       "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Honeycrisp",         "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Idared",             "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Jazz",               "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Jonagold",           "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Jonathan",           "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Liberty",            "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Macoun",             "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "McIntosh Red",       "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Melrose",            "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Opal",               "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Ozark Gold",         "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Pinata",             "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Pink Lady",          "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Pristine",           "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Red Delicious",      "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Rome",               "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Spartan",            "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Stayman",            "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "SweeTango",          "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "Winesap",            "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "",                   "Apple",                                    "Tasty.", "apple"),
(12, 1, 1, "",                   "Apricot",                                  "Tasty.", "apricot"),
(12, 1, 1, "",                   "Banana",                                   "Tasty.", "banana"),
(12, 1, 1, "",                   "Blackberries",                             "Tasty.", "blackberries"),
(12, 1, 1, "",                   "Blueberries",                              "Tasty.", "blueberries"),
(12, 1, 1, "",                   "Cherries",                                 "Tasty.", "cherries"),
(12, 1, 1, "Dried",              "Cranberries",                              "Tasty.", "cranberries"),
(12, 1, 1, "",                   "Cranberries",                              "Tasty.", "cranberries"),
(12, 1, 1, "Concord",            "Grapes",                                   "Tasty.", "grapes"),
(12, 1, 1, "Flame",              "Grapes",                                   "Tasty.", "grapes"),
(12, 1, 1, "Moon Drop",          "Grapes",                                   "Tasty.", "grapes"),
(12, 1, 1, "Ruby",               "Grapes",                                   "Tasty.", "grapes"),
(12, 1, 1, "Thompson",           "Grapes",                                   "Tasty.", "grapes"),
(12, 1, 1, "",                   "Grapes",                                   "Tasty.", "grapes"),
(12, 1, 1, "",                   "Guava",                                    "Tasty.", "guava"),
(12, 1, 1, "",                   "Kiwi",                                     "Tasty.", "kiwi"),
(12, 1, 1, "",                   "Mango",                                    "Tasty.", "mango"),
(12, 1, 1, "",                   "Watermelon",                               "Tasty.", "watermelon"),
(12, 1, 1, "",                   "Nectarine",                                "Tasty.", "nectarine"),
(12, 1, 1, "",                   "Papaya",                                   "Tasty.", "papaya"),
(12, 1, 1, "",                   "Peach",                                    "Tasty.", "peach"),
(12, 1, 1, "Anjou Green",        "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Anjou Red",          "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Asian",              "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Bartlett",           "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Bosc",               "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Comice",             "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Concord",            "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Forelle",            "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "French Butter",      "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Seckel",             "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "Taylor\'s Gold",     "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "",                   "Pear",                                     "Tasty.", "pear"),
(12, 1, 1, "",                   "Pineapple",                                "Tasty.", "pineapple"),
(12, 1, 1, "",                   "Orange",                                   "Tasty.", "orange"),
(12, 1, 1, "",                   "Raspberries",                              "Tasty.", "raspberries"),
(12, 1, 1, "",                   "Strawberries",                             "Tasty.", "strawberries"),
(12, 1, 1, "",                   "Tangerine",                                "Tasty.", "tangerine"),
(12, 1, 1, "",                   "Tangelo",                                  "Tasty.", "tangelo"),
(12, 1, 1, "",                   "Blood Orange",                             "Tasty.", "blood-orange"),
(12, 1, 1, "",                   "White Grapefruit",                         "Tasty.", "white-grapefruit"),
(12, 1, 1, "",                   "Pink Grapefruit",                          "Tasty.", "pink-grapefruit"),
(12, 1, 1, "",                   "Honeydew",                                 "Tasty.", "honeydew"),
(12, 1, 1, "",                   "Cantaloupe",                               "Tasty.", "cantaloupe"),
(12, 1, 1, "Italian",            "Plum",                                     "Tasty.", "italian-plum"),
(12, 1, 1, "",                   "Plum",                                     "Tasty.", "plum"),
(12, 1, 1, "",                   "Pomegranate",                              "Tasty.", "pomegranate"),

(13, 1, 1, "",                   "Almonds",                                  "Tasty.", "almonds"),
(13, 1, 1, "",                   "Brazil Nuts",                              "Tasty.", "almonds"),
(13, 1, 1, "",                   "Cashews",                                  "Tasty.", "cashews"),
(13, 1, 1, "",                   "Hazelnuts",                                "Tasty.", "almonds"),
(13, 1, 1, "",                   "Macadamia Nuts",                           "Tasty.", "almonds"),
(13, 1, 1, "",                   "Peacans",                                  "Tasty.", "almonds"),
(13, 1, 1, "",                   "Peanuts",                                  "Tasty.", "almonds"),
(13, 1, 1, "",                   "Pine Nuts",                                "Tasty.", "almonds"),
(13, 1, 1, "",                   "Pistachios",                               "Tasty.", "pistachios"),
(13, 1, 1, "",                   "Walnuts",                                  "Tasty.", "almonds"),

(14, 1, 1, "",                   "Chia Seeds",                               "Tasty.", "sesame-seeds"),
(14, 1, 1, "",                   "Hemp Seeds",                               "Tasty.", "sesame-seeds"),
(14, 1, 1, "",                   "Poppy Seeds",                              "Tasty.", "sesame-seeds"),
(14, 1, 1, "",                   "Pumpkin Seeds",                            "Tasty.", "pumpkin-seeds"),
(14, 1, 1, "",                   "Sesame Seeds",                             "Tasty.", "sesame-seeds"),
(14, 1, 1, "",                   "Quinoa",                                   "Tasty.", "sesame-seeds"),

(15, 1, 1, "Ancho",              "Pepper",                                   "Tasty.", "ancho-pepper"),
(15, 1, 1, "Arbol",              "Pepper",                                   "Tasty.", "arbol-pepper"),
(15, 1, 1, "Cascabel",           "Pepper",                                   "Tasty.", "cascabel-pepper"),
(15, 1, 1, "Guajillo",           "Pepper",                                   "Tasty.", "guajillo-pepper"),
(15, 1, 1, "Morita",             "Pepper",                                   "Tasty.", "morita-pepper"),
(15, 1, 1, "Mulato",             "Pepper",                                   "Tasty.", "mulato-pepper"),
(15, 1, 1, "Pasilla",            "Pepper",                                   "Tasty.", "pasilla-pepper"),
(15, 1, 1, "Pulla",              "Pepper",                                   "Tasty.", "pulla-pepper"),
(15, 1, 1, "",                   "Celery Seeds",                             "Tasty.", "celery-seeds"),
(15, 1, 1, "",                   "Cinnamon",                                 "Tasty.", "cinnamon"),
(15, 1, 1, "",                   "Ground Cinnamon",                          "Tasty.", "ground-cinnamon"),
(15, 1, 1, "",                   "Cloves",                                   "Tasty.", "cloves"),
(15, 1, 1, "",                   "Ground Cloves",                            "Tasty.", "ground-cloves"),
(15, 1, 1, "",                   "Caraway Seeds",                            "Tasty.", "cumin-seeds"),
(15, 1, 1, "",                   "Cumin Seeds",                              "Tasty.", "cumin-seeds"),
(15, 1, 1, "",                   "Cumin Powder",                             "Tasty.", "cumin-powder"),
(15, 1, 1, "",                   "Fennel Seeds",                             "Tasty.", "fennel-seeds"),
(15, 1, 1, "",                   "Garlic",                                   "Tasty.", "garlic"),
(15, 1, 1, "",                   "Garlic Powder",                            "Tasty.", "garlic-powder"),
(15, 1, 1, "",                   "Ginger",                                   "Tasty.", "ginger"),
(15, 1, 1, "",                   "Ginger Powder",                            "Tasty.", "ginger-powder"),
(15, 1, 1, "",                   "Shallots",                                 "Tasty.", "shallots"),
(15, 1, 1, "",                   "Turmeric",                                 "Tasty.", "turmeric"),
(15, 1, 1, "",                   "Turmeric Powder",                          "Tasty.", "turmeric-powder"),

(16, 1, 1, "",                   "Basil",                                    "Tasty.", "basil"),
(16, 1, 1, "",                   "Cilantro",                                 "Tasty.", "cilantro"),
(16, 1, 1, "",                   "Fenugreek",                                "Tasty.", "fenugreek"),
(16, 1, 1, "",                   "Parsley",                                  "Tasty.", "parsley"),
(16, 1, 1, "",                   "Rosemary",                                 "Tasty.", "rosemary"),
(16, 1, 1, "",                   "Sage",                                     "Tasty.", "sage"),
(16, 1, 1, "",                   "Thyme",                                    "Tasty.", "thyme"),

(17, 1, 1, "Apple Cider",        "Vinegar",                                  "Tasty.", "balsamic-vinegar"),
(17, 1, 1, "Balsamic",           "Vinegar",                                  "Tasty.", "balsamic-vinegar"),
(17, 1, 1, "Rice",               "Vinegar",                                  "Tasty.", "balsamic-vinegar"),

(18, 1, 1, "",                   "Fish Sauce",                               "Tasty.", "tobasco-sauce"),
(18, 1, 1, "Dark",               "Soy Sauce",                                "Tasty.", "tobasco-sauce"),
(18, 1, 1, "Light",              "Soy Sauce",                                "Tasty.", "tobasco-sauce"),
(18, 1, 1, "Tobasco",            "Hot Sauce",                                "Tasty.", "tobasco-sauce");

INSERT INTO recipes
(recipe_type_id, cuisine_id, author_id, owner_id, title, description, active_time, total_time, directions)
VALUES
(1,  1,  1, 1, "Borscht",                            "Excellent",        "00:30:00", "04:00:00", "Chop beets and onions..."),
(2,  2,  1, 1, "Soft Buttery Pretzle",               "Melting goodness", "00:20:00", "01:20:00", "Set oven to 400 F. Mix dough..."),
(3,  3,  1, 1, "Grilled Chicken and Seasoned Rice",  "Yum",              "01:00:00", "02:00:00", "Marinate chicken in a..."),
(4,  4,  1, 1, "Mixed Root Vegetables",              "Satisfying",       "00:15:00", "01:00:00", "Chop vegetables into about 2 inch by 2 inch pieces..."),
(5,  5,  1, 1, "Coffee Vanilla Icecream Cake",       "Special",          "00:30:00", "01:00:00", "Set oven to 275 F. Mix dough..."),
(6,  6,  1, 1, "Fish Carrot and Potato Soup",        "Nice.",            "00:45:00", "01:00:00", "Heat stock..."),
(7,  7,  1, 1, "Possibly Greek Salad",               "Who Knows",        "00:08:00", "00:08:00", "Mix olive oil and red wine vinegar in bowl..."),
(8,  8,  1, 1, "Irish Guinness Beef Stew",           "Calming",          "00:45:00", "04:00:00", "Sear well just one side of the beef pieces..."),
(9,  9,  1, 1, "Northern Chinese Seafood Casserole", "Excellent",        "00:45:00", "01:30:00", "Heat stock..."),
(10, 10, 1, 1, "Sweet Coconut Lime Sauce",           "Interesting",      "00:20:00", "00:20:00", "Mix..."),
(11, 11, 1, 1, "Carrot Ginger Dressing",             "Tasty",            "00:20:00", "00:20:00", "Blend carrots and..."),
(12, 12, 1, 1, "Some Kind Of Chutney",               "Not Bad",          "00:30:00", "01:00:00", "Mix...");

INSERT INTO recipe_equipment (recipe_id, amount, equipment_id) VALUES
(1,  1, 1),
(2,  1, 1),
(3,  1, 1),
(4,  1, 1),
(5,  1, 1),
(6,  1, 1),
(7,  1, 1),
(8,  1, 1),
(9,  1, 1),
(10, 1, 1),
(11, 1, 1),
(12, 1, 1);

INSERT INTO recipe_ingredients (recipe_id, amount, measurement_id, ingredient_id) VALUES
(1,  4,  1,  116),
(2,  2,  2,  209),
(3,  1,  3,  153),
(4,  1,  4,  159),
(5,  7,  5,  165),
(6,  1,  6,  176),
(7,  3,  7,  142),
(8,  1,  8,  230),
(9,  9,  9,  202),
(10, 20, 10, 100),
(11, 10,  1, 122),
(12, 13,  2, 138);

INSERT INTO recipe_methods (recipe_id, method_id) VALUES
(1,  6),
(2,  9),
(3,  13),
(4,  15),
(5,  16),
(6,  7),
(7,  4),
(8,  3),
(9,  2),
(10, 1),
(11, 12),
(12, 13);



CREATE FULLTEXT INDEX fulltext_idx_name ON equipment (name);

CREATE FULLTEXT INDEX fulltext_idx_brand   ON ingredients (brand);
CREATE FULLTEXT INDEX fulltext_idx_variety ON ingredients (variety);
CREATE FULLTEXT INDEX fulltext_idx_name    ON ingredients (name);

CREATE FULLTEXT INDEX fulltext_idx_brand   ON products (brand);
CREATE FULLTEXT INDEX fulltext_idx_variety ON products (variety);
CREATE FULLTEXT INDEX fulltext_idx_name    ON products (name);

CREATE FULLTEXT INDEX fulltext_idx_title ON recipes (title);
