version: "3.8"

services:

  mysql-dev:
    image: mysql:latest
    volumes:
      - mysql-dev:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    #command: --disable-partition-engine-check
    #Note: This healthcheck test can return false positive, find a better one
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"
  
  redis-dev:
    image: redis:latest
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis-dev:/data
    ports:
      - "6379:6379"

  nobsc-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    #command: node_modules/.bin/nodemon app/index.js
    depends_on:
      mysql-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    #volumes:
      #- ./src/:/api/src
      #- /node/app/node_modules
    env_file: .env
    environment:
      NODE_ENV: development
      NODE_PATH: /api/node_modules
      PORT: 3003
    ports:
      - "3003:3003"

volumes:
  mysql-dev:
  redis-dev: