version: "2.2"

services:

  mysql-dev:
    image: mysql:8
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    #volumes:
    #  - dbdata:/var/lib/mysql
    restart: always
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:5
    healthcheck:
      test: redis-cli ping
    #volumes:
    #  - cachedata:/data
    ports:
      - "6379:6379"

  nobsc-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    #restart: always
    #working_dir: ./
    depends_on:
      mysql-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    volumes:
      - .:/node/app
      - /node/app/node_modules
    env_file: .env
    ports:
      - "3003:3003"

volumes:
  mysql-dev:
  redis-dev: