version: "2.4"

services:
  # MySQL
  mysql-dev:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"

  # Redis
  redis-dev:
    image: redis
    volumes:
      - cachedata:/data
    ports:
      - "6379:6379"

  # NOBSC API
  nobsc-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    restart: always
    #working_dir: ./
    depends_on:
      - mysql-dev
      - redis-dev
    volumes:
      - .:/node/app
      - /node/app/node_modules
    env_file: .env
    ports:
      - "3003:3003"

volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local