version: "3.8"

services:

  mysql-test:
    image: mysql:latest
    volumes:
      - mysql-test:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    #command: --disable-partition-engine-check
    #Note: This healthcheck test can return false positive, find a better one
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"
  
  redis-test:
    image: redis:latest
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis-test:/data
    ports:
      - "6379:6379"
  
  nobsc-api-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    depends_on:
      mysql-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    #env_file: .env
    environment:
      NODE_ENV: test
      NODE_PATH: /api/node_modules
      PORT: 3003
      TEST_MYSQL_URI: mysql://root:password@localhost:3306/nobsc
      TEST_MYSQL_HOST: mysql-test
      TEST_MYSQL_DATABASE: nobsc
      TEST_MYSQL_USER: root
      TEST_MYSQL_PASSWORD: pass
      TEST_MYSQL_ROOT_PASSWORD: pass
      TEST_REDIS_URI: redis://redis:6379
      TEST_REDIS_HOST: redis-test
      TEST_REDIS_PORT: 6379
    ports:
      - "3003:3003"

volumes:
  mysql-test:
  redis-test: