version: "3.9"

services:

  mysql-dev:
    image: mysql:latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-dev:/var/lib/mysql
    command: mysqld --default-authentication-plugin=caching_sha2_password
    #command: --disable-partition-engine-check
    # The healthcheck test immediately below can return a false positive. TO DO: Find a better solution.
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"
  
  redis-dev:
    image: redis:latest
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis-dev:/data
    ports:
      - "6379:6379"

  nobsc-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      mysql-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file: .env
    environment:
      NODE_ENV: development
      NODE_PATH: /app/node_modules
      PORT: 3003
    ports:
      - "3003:3003"

volumes:
  mysql-dev:
  redis-dev: