#1

FROM mysql:latest

COPY ./dbdata/test.sql /dbdata/test.sql

#2

FROM node:16.19.0

EXPOSE 3003

WORKDIR /api
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install && npm cache clean --force

#necessary?
WORKDIR /api/types
COPY ./types .

WORKDIR /api/src
COPY ./src .

CMD npm run dev-ts