version: "2.2"

services:

  mysql-dev:
    image: mysql:8.0.17
    volumes:
      - mysql-dev:/var/lib/mysql
    #image: mysql:5.7.27
    command: mysqld --default-authentication-plugin=mysql_native_password
    #command: --disable-partition-engine-check
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:5.0.5
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis-dev:/data
    ports:
      - "6379:6379"

  nobsc-api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    #restart: always
    depends_on:
      mysql-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    volumes:
      #- ./:/node/app  can't find, why???
      - /node/app/node_modules
    env_file: .env
    environment:
      NODE_ENV: development
      PORT: 3003
    ports:
      - "3003:3003"
      - "9229:9229"

volumes:
  mysql-dev:
  redis-dev: