#1

FROM mysql:8.0.17

#ADD ./dbdata/ /docker-entrypoint-initdb.d/
COPY ./dbdata/test.sql /dbdata/test.sql

#2

FROM node:10.16.0

EXPOSE 3003

WORKDIR /api
COPY package*.json ./
RUN npm install && npm cache clean --force
#COPY . .

WORKDIR /api/src
COPY ./src .
#CMD /node/node_modules/.bin/webpack-dev-server --config webpack.dev.js --mode development --open --hot --host 0.0.0.0 --port 3003
#CMD /node/node_modules/.bin/nodemon src/index.js
#CMD node --inspect=0.0.0.0:9229 src/index.js
CMD node index.js