#1

FROM mysql:8.0.21

COPY ./dbdata/test.sql /dbdata/test.sql

#2

FROM node:12.17.0

EXPOSE 3003

WORKDIR /api
COPY global-setup.js ./
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install && npm cache clean --force

WORKDIR /api/src
COPY ./src .

WORKDIR /api/tests
COPY ./tests .

CMD npm run test