FROM node:10.16.0

WORKDIR /node

#ENV PATH node/app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install && npm cache clean --force

WORKDIR /node/app

COPY . .

CMD /node/node_modules/.bin/webpack-dev-server --config webpack.dev.js --mode development --open --hot --host 0.0.0.0