version: "2.2"

services:

  mysql-dev:
    image: mysql:8.0.17
    volumes:
      - mysql-dev:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    #command: --disable-partition-engine-check
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:5.0.5
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis-dev:/data
    ports:
      - "6379:6379"
      - "6380:6380"
      - "6381:6381"

  nobsc-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    #command: node_modules/.bin/nodemon app/index.js
    depends_on:
      mysql-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    #volumes:
      #- ./src/:/api/src
      #- /node/app/node_modules
    env_file: .env
    environment:
      NODE_ENV: development
      NODE_PATH: /api/node_modules
      PORT: 3003
    ports:
      - "3003:3003"
      - "9229:9229"

volumes:
  mysql-dev:
  redis-dev: