version: "2.2"

services:

  mysql-test:
    image: mysql:8.0.21
    volumes:
      - mysql-test:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    #command: --disable-partition-engine-check
    #Note: This healthcheck test can return false positive, find a better one
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_DATABASE: nobsc
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
  
  elasticsearch-test:
    image: elasticsearch:7.8.0
    depends_on:
      mysql-test:
        condition: service_healthy
    healthcheck:
      test: curl localhost:9200/_cluster/health
    volumes:
      - elasticsearch-test:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      #- node.name=elasticsearch-test
    ports:
      - "9200:9200"
      - "9300:9300"
  
  #kibana-test:
    #image: kibana:7.3.1
    #ports:
      #- "5602:5602"
  
  redis-test:
    healthcheck:
      test: redis-cli ping
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-test:/data
  
  nobsc-api-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    command: "npm run test -- --coverage --watchAll=false"
    depends_on:
      mysql-test:
        condition: service_healthy
      elasticsearch-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    #env_file: .env
    environment:
      NODE_ENV: test
      NODE_PATH: /api/node_modules
      PORT: 3003
      TEST_MYSQL_URI: mysql://root:password@localhost:3306/nobsc
      TEST_MYSQL_HOST: mysql-test
      TEST_MYSQL_DATABASE: nobsc
      TEST_MYSQL_USER: root
      TEST_MYSQL_PASSWORD: pass
      TEST_MYSQL_ROOT_PASSWORD: pass
      TEST_REDIS_URI: redis://redis:6379
      TEST_REDIS_HOST: redis-test
      TEST_REDIS_PORT: 6379
    ports:
      - "3003:3003"
      - "9229:9229"

volumes:
  mysql-test:
  elasticsearch-test:
  redis-test: