version: "2.2"

services:

  mysql-dev:
    image: mysql:8.0.17
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    volumes:
      - mysql-dev:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: root
      MYSQL_DATABASE: nobsc
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:5.0.5
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis-dev:/data
    ports:
      - "6379:6379"
    #command: redis-server --bind 0.0.0.0 --port 6379
    #command: redis-server status

  nobsc-api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    #restart: always
    #command: /node/node_modules/.bin/webpack-dev-server --config webpack.dev.js --mode development --open --hot --host 0.0.0.0
    #working_dir: ./
    depends_on:
      mysql-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    volumes:
      #- ./:/node/app  can't find, why???
      - /node/app/node_modules
    env_file: .env
    environment:
      NODE_ENV: development
      PORT: 3003
    ports:
      - "3003:3003"
      - "9229:9229"

volumes:
  mysql-dev:
  redis-dev: