#1

FROM mysql:latest

COPY ./dbdata/test.sql /dbdata/test.sql

#2

FROM node:16.19.0

EXPOSE 3003

WORKDIR /api
COPY global-setup.js ./
COPY jest.config.js ./
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install && npm cache clean --force

#necessary?
WORKDIR /api/types
COPY ./types .

WORKDIR /api/src
COPY ./src .

WORKDIR /api/tests
COPY ./tests .

CMD npm run test -- --coverage --logHeapUsage --runInBand --watchAll=false