version: 2.1
jobs:
  build:
    docker:
      - image: docker.elastic.co/elasticsearch/elasticsearch
      - image: circleci/mysql
      - image: circleci/redis
      - image: circleci/node:10.16.3
    working_directory: ~/nobullshitcooking-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
