INSERT INTO nobsc_methods
(method_id, method_name)
VALUES
(1, "No-Cook"),
(2, "Chill"),
(3, "Freeze"),
(4, "Microwave"),
(5, "Toast"),
(6, "Steam"),
(7, "Poach"),
(8, "Simmer"),
(9, "Boil"),
(10, "Blanch"),
(11, "Stew"),
(12, "Braise"),
(13, "Bake"),
(14, "Roast"),
(15, "Broil"),
(16, "Saute"),
(17, "Pan-Fry"),
(18, "Shallow-Fry"),
(19, "Deep-Fry"),
(20, "Stir-Fry"),
(21, "Glaze"),
(22, "BBQ"),
(23, "Grill"),
(24, "Smoke");