INSERT INTO nobsc_ingredients
(ingredient_type_id, author_id, owner_id, ingredient_name, ingredient_description, ingredient_image)
VALUES
(3, 1, 1, "Chuck Seven Bone Roast", "Tasty.", "nobsc-chuck-7-bone-roast"),
(3, 1, 1, "Chuck Seven Bone Steak", "Tasty.", "nobsc-chuck-7-bone-steak"),
(3, 1, 1, "Chuck Arm Roast", "Tasty.", "nobsc-chuck-arm-roast"),
(3, 1, 1, "Chuck Arm Roast Boneless", "Tasty.", "nobsc-chuck-arm-rost-boneless"),
(3, 1, 1, "Chuck Arm Steak", "Tasty.", "nobsc-chuck-arm-steak"),
(3, 1, 1, "Chuck Arm Steak Boneless", "Tasty.", "nobsc-chuck-arm-steak-boneless"),
(3, 1, 1, "Chuck Blade Roast", "Tasty.", "nobsc-chuck-blade-roast"),
(3, 1, 1, "Chuck Blade Steak", "Tasty.", "nobsc-chuck-blade-steak"),
(3, 1, 1, "Chuck Blade Steak Boneless", "Tasty.", "nobsc-chuck-blade-steak-boneless"),
(3, 1, 1, "Chuck Blade Steak Cap Off", "Tasty.", "nobsc-chuck-blade-steak-cap-off"),

(3, 1, 1, "Chuck Cross Rib Roast", "Tasty.", "nobsc-chuck-cross-rib-roast"),
(3, 1, 1, "Chuck Cross Rib Roast Boneless", "Tasty.", "nobsc-chuck-cross-rib-roast-boneless"),
(3, 1, 1, "Chuck Eye Edge Roast", "Tasty.", "nobsc-chuck-eye-edge-roast"),
(3, 1, 1, "Chuck Eye Roast Boneless", "Tasty.", "nobsc-chuck-eye-roast-steak"),
(3, 1, 1, "Chuck Eye Steak Boneless", "Tasty.", "nobsc-chuck-eye-steak-boneless"),
(3, 1, 1, "Chuck Flanken Style Ribs", "Tasty.", "nobsc-chuck-flanken-style-ribs"),
(3, 1, 1, "Chuck Flanken Style Ribs Boneless", "Tasty.", "nobsc-chuck-flanken-style-ribs-boneless"),
(3, 1, 1, "Chuck Flat Ribs", "Tasty.", "nobsc-chuck-flat-ribs"),
(3, 1, 1, "Chuck Mock Tender Roast", "Tasty.", "nobsc-chuck-mock-tender-roast"),
(3, 1, 1, "Chuck Mock Tender Steak", "Tasty.", "nobsc-chuck-mock-tender-steak"),

(3, 1, 1, "Chuck Neck Roast", "Tasty.", "nobsc-chuck-neck-roast"),
(3, 1, 1, "Chuck Neck Roast Boneless", "Tasty.", "nobsc-chuck-neck-roast-boneless"),
(3, 1, 1, "Chuck Roast Boneless", "Tasty.", "nobsc-chuck-roast-boneless"),
(3, 1, 1, "Chuck Short Ribs", "Tasty.", "nobsc-chuck-short-ribs"),
(3, 1, 1, "Chuck Short Ribs Boneless", "Tasty.", "nobsc-chuck-short-ribs-boneless"),
(3, 1, 1, "Chuck Shoulder Center Steak Ranch Steak", "Tasty.", "nobsc-chuck-shoulder-center-steak-ranch-steak"),
(3, 1, 1, "Chuck Shoulder Roast", "Tasty.", "nobsc-chuck-shoulder-roast"),
(3, 1, 1, "Chuck Shoulder Roast Boneless", "Tasty.", "nobsc-chuck-shoulder-roast-boneless"),
(3, 1, 1, "Chuck Shoulder Steak Boneless", "Tasty.", "nobsc-chuck-shoulder-steak-boneless"),
(3, 1, 1, "Chuck Shoulder Tender", "Tasty.", "nobsc-chuck-shoulder-tender"),

(3, 1, 1, "Chuck Shoulder Tender Medallions", "Tasty.", "nobsc-chuck-shoulder-tender-medallions"),
(3, 1, 1, "Chuck Shoulder Top Blade Roast Boneless", "Tasty.", "nobsc-chuck-shoulder-top-blade-roast-boneless"),
(3, 1, 1, "Chuck Shoulder Top Blade Steak Boneless", "Tasty.", "nobsc-chuck-shoulder-top-blade-steak-boneless"),
(3, 1, 1, "Chuck Shoulder Top Blade Steak Flat Iron", "Tasty.", "nobsc-chuck-shoulder-top-blade-steak-flat-iron"),
(3, 1, 1, "Chuck Top Blade Roast", "Tasty.", "nobsc-chuck-top-blade-roast"),
(3, 1, 1, "Chuck Top Blade Steak Bone In", "Tasty.", "nobsc-chuck-top-blade-steak-bone-in"),
(3, 1, 1, "Chuck Under Blade Roast", "Tasty.", "nobsc-chuck-under-blade-roast"),
(3, 1, 1, "Chuck Under Blade Roast Boneless", "Tasty.", "nobsc-chuck-under-blade-roast-boneless"),
(3, 1, 1, "Chuck Under Blade Steak", "Tasty.", "nobsc-chuck-under-blade-steak"),
(3, 1, 1, "Chuck Under Blade Steak Boneless", "Tasty.", "nobsc-chuck-under-blade-steak-boneless"),

(3, 1, 1, "Round Bottom Round Roast", "Tasty.", "nobsc-round-bottom-round-roast"),
(3, 1, 1, "Round Bottom Round Roast Triangle Roast", "Tasty.", "nobsc-round-bottom-round-roast-triangle-roast"),
(3, 1, 1, "Round Bottom Round Rump Roast", "Tasty.", "nobsc-round-bottom-round-rump-roast"),
(3, 1, 1, "Round Bottom Round Steak", "Tasty.", "nobsc-round-bottom-round-steak"),
(3, 1, 1, "Round Bottom Round Steak Western Griller", "Tasty.", "nobsc-round-bottom-round-steak-western-griller"),
(3, 1, 1, "Round Eye Round Roast", "Tasty.", "nobsc-round-eye-round-roast"),
(3, 1, 1, "Round Eye Round Steak", "Tasty.", "nobsc-round-eye-round-steak"),
(3, 1, 1, "Round Heel of Round", "Tasty.", "nobsc-round-heel-of-round"),
(3, 1, 1, "Round Sirloin Tip Center Roast", "Tasty.", "nobsc-round-sirloin-tip-center-roast"),
(3, 1, 1, "Round Sirloin Tip Center Steak", "Tasty.", "nobsc-round-sirloin-tip-center-steak"),

(3, 1, 1, "Round Sirloin Tip Side Steak", "Tasty.", "nobsc-round-sirloin-tip-side-steak"),
(3, 1, 1, "Round Steak", "Tasty.", "nobsc-round-steak"),
(3, 1, 1, "Round Steak Boneless", "Tasty.", "nobsc-round-steak-boneless"),
(3, 1, 1, "Round Tip Roast", "Tasty.", "nobsc-round-tip-roast"),
(3, 1, 1, "Round Tip Roast Cap Off", "Tasty.", "nobsc-round-tip-roast-cap-off"),
(3, 1, 1, "Round Tip Steak", "Tasty.", "nobsc-round-tip-steak"),
(3, 1, 1, "Round Tip Steak Cap Off", "Tasty.", "nobsc-round-tip-steak-cap-off"),
(3, 1, 1, "Round Top Round Roast", "Tasty.", "nobsc-round-top-round-roast"),
(3, 1, 1, "Round Top Round Roast Cap Off", "Tasty.", "nobsc-round-top-round-roast-cap-off"),
(3, 1, 1, "Round Top Round Steak", "Tasty.", "nobsc-round-top-round-steak"),

(3, 1, 1, "Round Top Round Steak Butterflied", "Tasty.", "nobsc-round-top-round-steak-butterflied"),
(3, 1, 1, "Round Top Round Steak First Cut", "Tasty.", "nobsc-round-top-round-steak-first-cut"),
(3, 1, 1, "Loin Ball Tip Roast", "Tasty.", "nobsc-loin-ball-tip-roast"),
(3, 1, 1, "Loin Ball Tip Steak", "Tasty.", "nobsc-loin-ball-tip-steak"),
(3, 1, 1, "Loin Flap Meat Steak", "Tasty.", "nobsc-loin-flap-meat-steak"),
(3, 1, 1, "Loin Porterhouse Steak", "Tasty.", "nobsc-loin-porterhouse-steak"),
(3, 1, 1, "Loin Shell Sirloin Steak", "Tasty.", "nobsc-loin-shell-sirloin-steak"),
(3, 1, 1, "Loin Sirloin Steak", "Tasty.", "nobsc-loin-sirloin-steak"),
(3, 1, 1, "Loin T Bone Steak", "Tasty.", "nobsc-loin-t-bone-steak"),
(3, 1, 1, "Loin Tenderloin Roast", "Tasty.", "nobsc-loin-tenderloin-roast"),

(3, 1, 1, "Loin Tenderloin Steak", "Tasty.", "nobsc-loin-tenderloin-steak"),
(3, 1, 1, "Loin Top Loin Roast", "Tasty.", "nobsc-loin-top-loin-roast"),
(3, 1, 1, "Loin Top Loin Roast Boneless", "Tasty.", "nobsc-loin-top-loin-roast-boneless"),
(3, 1, 1, "Loin Top Loin Steak", "Tasty.", "nobsc-loin-top-loin-steak"),
(3, 1, 1, "Loin Top Loin Steak Boneless", "Tasty.", "nobsc-loin-top-loin-steak-boneless"),
(3, 1, 1, "Loin Top Sirloin Roast Boneless", "Tasty.", "nobsc-loin-top-sirloin-roast-boneless"),
(3, 1, 1, "Loin Top Sirloin Roast Boneless Cap Off", "Tasty.", "nobsc-loin-top-sirloin-roast-boneless-cap-off"),
(3, 1, 1, "Loin Top Sirloin Steak Boneless", "Tasty.", "nobsc-loin-top-sirloin-steak-boneless"),
(3, 1, 1, "Loin Top Sirloin Steak Boneless Cap Off", "Tasty.", "nobsc-loin-top-sirloin-steak-boneless-cap-off"),
(3, 1, 1, "Loin Tri Tip Roast", "Tasty.", "nobsc-loin-tri-tip-roast"),

(3, 1, 1, "Loin Tri Tip Steak", "Tasty.", "nobsc-loin-tri-tip-steak"),
(3, 1, 1, "Shank Cross Cut", "Tasty.", "nobsc-shank-cross-cut"),
(3, 1, 1, "Shank Cross Cut Boneless", "Tasty.", "nobsc-shank-cross-cut-boneless"),
(3, 1, 1, "Plate Skirt Steak", "Tasty.", "nobsc-plate-skirt-steak"),
(3, 1, 1, "Flank Steak", "Tasty.", "nobsc-flank-flank-steak"),
(3, 1, 1, "Ground Beef", "Tasty.", "nobsc-ground-beef"),
(3, 1, 1, "Back Ribs", "Tasty.", "nobsc-back-ribs"),
(3, 1, 1, "Rib Cap Meat Boneless", "Tasty.", "nobsc-rib-cap-meat-boneless"),
(3, 1, 1, "Rib Extra Trim Roast Large End", "Tasty.", "nobsc-rib-extra-trim-roast-large-end"),
(3, 1, 1, "Ribeye Roast", "Tasty.", "nobsc-ribeye-roast"),

(3, 1, 1, "Ribeye Roast Lip On Bone In", "Tasty.", "nobsc-ribeye-roast-lip-on-bone-in"),
(3, 1, 1, "Ribeye Roast Lip On Boneless", "Tasty.", "nobsc-ribeye-roast-lip-on-boneless"),
(3, 1, 1, "Ribeye Steak", 3, "nobsc-ribeye-steak"),
(3, 1, 1, "Ribeye Steak Lip On Bone In", "Tasty.", "nobsc-ribeye-steak-lip-on-bone-in"),
(3, 1, 1, "Ribeye Steak Lip On Boneless", "Tasty.", "nobsc-ribeye-steak-lip-on-boneless"),
(3, 1, 1, "Rib Roast Large End", "Tasty.", "nobsc-rib-roast-large-end"),
(3, 1, 1, "Rib Roast Large End Boneless", "Tasty.", "nobsc-rib-roast-large-end-boneless"),
(3, 1, 1, "Rib Roast Small End", "Tasty.", "nobsc-rib-roast-small-end"),
(3, 1, 1, "Rib Roast Small End Boneless", "Tasty.", "nobsc-rib-roast-small-end-boneless"),
(3, 1, 1, "Rib Rolled Cap Pot Roast Boneless", "Tasty.", "nobsc-rib-rolled-cap-pot-roast-boneless"),

(3, 1, 1, "Rib Short Ribs", "Tasty.", "nobsc-rib-short-ribs"),
(3, 1, 1, "Rib Short Ribs Boneless", "Tasty.", "nobsc-rib-short-ribs-boneless"),
(3, 1, 1, "Rib Steak Large End", "Tasty.", "nobsc-rib-steak-large-end"),
(3, 1, 1, "Rib Steak Small End", "Tasty.", "nobsc-rib-steak-small-end"),
(3, 1, 1, "Rib Steak Small End Boneless", "Tasty.", "nobsc-rib-steak-small-end-boneless"),
(13, 1, 1, "Almonds", "Tasty.", "nobsc-almonds"),
(13, 1, 1, "Cashews", "Tasty.", "nobsc-cashews"),
(13, 1, 1, "Pistachios", "Tasty.", "nobsc-pistachios"),
(14, 1, 1, "Pumpkin Seeds", "Tasty.", "nobsc-pumpkin-seeds"),
(14, 1, 1, "Sesame Seeds", "Tasty.", "nobsc-sesame-seeds"),

(12, 1, 1, "Apple", "Tasty.", "nobsc-apple"),
(12, 1, 1, "Apricot", "Tasty.", "nobsc-apricot"),
(12, 1, 1, "Banana", "Tasty.", "nobsc-banana"),
(12, 1, 1, "Blackberries", "Tasty.", "nobsc-blackberries"),
(12, 1, 1, "Blueberries", "Tasty.", "nobsc-blueberries"),
(12, 1, 1, "Cherries", "Tasty.", "nobsc-cherries"),
(12, 1, 1, "Cranberries", "Tasty.", "nobsc-cranberries"),
(12, 1, 1, "Grapes", "Tasty.", "nobsc-grapes"),
(12, 1, 1, "Guava", "Tasty.", "nobsc-guava"),
(12, 1, 1, "Kiwi", "Tasty.", "nobsc-kiwi"),

(12, 1, 1, "Mango", "Tasty.", "nobsc-mango"),
(12, 1, 1, "Watermelon", "Tasty.", "nobsc-watermelon"),
(12, 1, 1, "Nectarine", "Tasty.", "nobsc-nectarine"),
(12, 1, 1, "Papaya", "Tasty.", "nobsc-papaya"),
(12, 1, 1, "Peach", "Tasty.", "nobsc-peach"),
(12, 1, 1, "Pear", "Tasty.", "nobsc-pear"),
(12, 1, 1, "Pineapple", "Tasty.", "nobsc-pineapple"),
(12, 1, 1, "Orange", "Tasty.", "nobsc-orange"),
(12, 1, 1, "Raspberries", "Tasty.", "nobsc-raspberries"),
(12, 1, 1, "Strawberries", "Tasty.", "nobsc-strawberries"),

(12, 1, 1, "Tangerine", "Tasty.", "nobsc-tangerine"),
(12, 1, 1, "Tangelo", "Tasty.", "nobsc-tangelo"),
(12, 1, 1, "Blood Orange", "Tasty.", "nobsc-blood-orange"),
(12, 1, 1, "White Grapefruit", "Tasty.", "nobsc-white-grapefruit"),
(12, 1, 1, "Pink Grapefruit", "Tasty.", "nobsc-pink-grapefruit"),
(12, 1, 1, "Honeydew", "Tasty.", "nobsc-honeydew"),
(12, 1, 1, "Cantaloupe", "Tasty.", "nobsc-cantaloupe"),
(12, 1, 1, "Plum", "Tasty.", "nobsc-plum"),
(12, 1, 1, "Italian Plum", "Tasty.", "nobsc-italian-plum"),
(12, 1, 1, "Pomegranate", "Tasty.", "nobsc-pomegranate"),

(11, 1, 1, "Broccoli", "Tasty.", "nobsc-broccoli"),
(11, 1, 1, "Brussels Sprouts", "Tasty.", "nobsc-brussels-sprouts"),
(11, 1, 1, "Bok Choy", "Tasty.", "nobsc-bok-choy"),
(11, 1, 1, "Green Cabbage", "Tasty.", "nobsc-green-cabbage"),
(11, 1, 1, "Red Cabbage", "Tasty.", "nobsc-red-cabbage"),
(11, 1, 1, "Napa Cabbage Chinese Cabbage", "Tasty.", "nobsc-napa-cabbage-chinese-cabbage"),
(11, 1, 1, "Savoy Cabbage", "Tasty.", "nobsc-savoy-cabbage"),
(11, 1, 1, "Cauliflower", "Tasty.", "nobsc-cauliflower"),
(11, 1, 1, "Kohlrabi", "Tasty.", "nobsc-kohlrabi"),
(11, 1, 1, "Collard Greens", "Tasty.", "nobsc-collard-greens"),

(11, 1, 1, "Kale", "Tasty.", "nobsc-kale"),
(11, 1, 1, "Turnip Greens", "Tasty.", "nobsc-turnip-greens"),
(11, 1, 1, "Pak Choy Baby Bok Choy", "Tasty.", "nobsc-pak-choy-baby-bok-choy"),
(11, 1, 1, "Zucchini", "Tasty.", "nobsc-zucchini"),
(11, 1, 1, "Standard Slicing Cucumber", "Tasty.", "nobsc-standard-slicing-cucumber"),
(11, 1, 1, "Purple Eggplant", "Tasty.", "nobsc-purple-eggplant"),
(11, 1, 1, "White Eggplant", "Tasty.", "nobsc-white-eggplant"),
(11, 1, 1, "Japanese Eggplant", "Tasty.", "nobsc-japanese-eggplant"),
(11, 1, 1, "Acorn Squash", "Tasty.", "nobsc-acorn-squash"),
(11, 1, 1, "Butternut Squash", "Tasty.", "nobsc-butternut-squash"),

(11, 1, 1, "Hubbard Squash", "Tasty.", "nobsc-hubbard-squash"),
(11, 1, 1, "Pumpkin", "Tasty.", "nobsc-pumpkin"),
(11, 1, 1, "Spaghetti Squash", "Tasty.", "nobsc-spaghetti-squash"),
(11, 1, 1, "Delicata Squash", "Tasty.", "nobsc-delicata-squash"),
(11, 1, 1, "Boston Lettuce", "Tasty.", "nobsc-boston-lettuce"),
(11, 1, 1, "Bibb Lettuce", "Tasty.", "nobsc-bibb-lettuce"),
(11, 1, 1, "Iceberg Lettuce", "Tasty.", "nobsc-iceberg-lettuce"),
(11, 1, 1, "Romaine Lettuce", "Tasty.", "nobsc-romaine-lettuce"),
(11, 1, 1, "Green Leaf Lettuce", "Tasty.", "nobsc-green-leaf-lettuce"),
(11, 1, 1, "Oak Leaf Lettuce", "Tasty.", "nobsc-oak-leaf-lettuce"),

(11, 1, 1, "Red Leaf Lettuce", "Tasty.", "nobsc-red-leaf-lettuce"),
(11, 1, 1, "Arugula Rocket", "Tasty.", "nobsc-arugula-rocket"),
(11, 1, 1, "Belgian Endive", "Tasty.", "nobsc-belgian-endive"),
(11, 1, 1, "Frisee", "Tasty.", "nobsc-frisee"),
(11, 1, 1, "Escarole", "Tasty.", "nobsc-escarole"),
(11, 1, 1, "Mache Lambs Lettuce", "Tasty.", "nobsc-mache-lambs-lettuce"),
(11, 1, 1, "Radicchio", "Tasty.", "nobsc-radicchio"),
(11, 1, 1, "Watercress", "Tasty.", "nobsc-watercress"),
(11, 1, 1, "Spinach", "Tasty.", "nobsc-spinach"),
(11, 1, 1, "Swiss Chard", "Tasty.", "nobsc-swiss-chard"),

(11, 1, 1, "Beet Greens", "Tasty.", "nobsc-beet-greens"),
(11, 1, 1, "Dandelion Greens", "Tasty.", "nobsc-dandelion-greens"),
(11, 1, 1, "Mustard Greens", "Tasty.", "nobsc-mustard-greens"),
(11, 1, 1, "Shiitake Mushrooms", "Tasty.", "nobsc-shiitake-mushrooms"),
(11, 1, 1, "Cremini Mushrooms", "Tasty.", "nobsc-cremini-mushrooms"),
(11, 1, 1, "Portobello Mushrooms", "Tasty.", "nobsc-portobello-mushrooms"),
(11, 1, 1, "Pearl Onions", "Tasty.", "nobsc-pearl-onions"),
(11, 1, 1, "Globe Onion", "Tasty.", "nobsc-globe-onion"),
(11, 1, 1, "Spanish Onion", "Tasty.", "nobsc-spanish-onion"),
(11, 1, 1, "Sweet Onion", "Tasty.", "nobsc-sweet-onion"),

(11, 1, 1, "Garlic", "Tasty.", "nobsc-garlic"),
(11, 1, 1, "Shallots", "Tasty.", "nobsc-shallots"),
(11, 1, 1, "Leek", "Tasty.", "nobsc-leek"),
(11, 1, 1, "Scallion Green Onion", "Tasty.", "nobsc-scallion-green-onion"),
(11, 1, 1, "Bell Pepper", "Tasty.", "nobsc-bell-pepper"),
(11, 1, 1, "Poblano Pepper", "Tasty.", "nobsc-poblano-pepper"),
(11, 1, 1, "Jalapeno Pepper", "Tasty.", "nobsc-jalapeno-pepper"),
(11, 1, 1, "Serrano Pepper", "Tasty.", "nobsc-serrano-pepper"),
(11, 1, 1, "Thai Pepper", "Tasty.", "nobsc-thai-pepper"),
(11, 1, 1, "Habanero Pepper", "Tasty.", "nobsc-habanero-pepper"),

(11, 1, 1, "Baby Spinach", "Tasty.", "nobsc-baby-spinach"),
(11, 1, 1, "Beets", "Tasty.", "nobsc-beets"),
(11, 1, 1, "Mushrooms", "Tasty.", "nobsc-mushrooms"),
(11, 1, 1, "Onion", "Tasty.", "nobsc-onion"),
(11, 1, 1, "Winterbor Kale Curly Kale", "Tasty.", "nobsc-winterbor-kale-curly-kale"),
(11, 1, 1, "Red Russian Kale", "Tasty.", "nobsc-red-russian-kale"),
(11, 1, 1, "Grape Tomatoes", "Tasty.", "nobsc-grape-tomatoes"),
(11, 1, 1, "Green Beans", "Tasty.", "nobsc-green-beans"),
(11, 1, 1, "Green Peas", "Tasty.", "nobsc-green-peas")
(11, 1, 1, "Celery", "Tasty.", "nobsc-celery"),

(11, 1, 1, "Asparagus", "Tasty.", "nobsc-asparagus"),
(11, 1, 1, "Snowpeas", "Tasty.", "nobsc-snowpeas"),
(11, 1, 1, "Sugar Snap Peas", "Tasty.", "nobsc-sugar-snap-peas"),
(11, 1, 1, "Carrots", "Tasty.", "nobsc-carrots"),
(11, 1, 1, "Parsnips", "Tasty.", "nobsc-parsnips"),
(11, 1, 1, "Turnips", "Tasty.", "nobsc-turnips"),
(11, 1, 1, "White Turnips", "Tasty.", "nobsc-white-turnips"),
(11, 1, 1, "Radishes", "Tasty.", "nobsc-radishes"),
(11, 1, 1, "French Radishes", "Tasty.", "nobsc-french-radishes"),
(11, 1, 1, "Baby Gold Beets", "Tasty.", "nobsc-baby-gold-beets"),

(11, 1, 1, "Red Beets", "Tasty.", "nobsc-red-beets"),
(11, 1, 1, "Daikon", "Tasty.", "nobsc-daikon"),
(11, 1, 1, "Horseradish", "Tasty.", "nobsc-horseradish"),
(11, 1, 1, "Rutabaga", "Tasty.", "nobsc-rutabaga"),
(11, 1, 1, "Ginger", "Tasty.", "nobsc-ginger"),
(11, 1, 1, "Sunchoke Jerusalem Artichoke", "Tasty.", "nobsc-sunchoke-jerusalem-artichoke"),
(11, 1, 1, "Fennel", "Tasty.", "nobsc-fennel"),
(11, 1, 1, "Tomatillo", "Tasty.", "nobsc-tomatillo"),
(11, 1, 1, "Standard Beefsteak Tomatoes", "Tasty.", "nobsc-standard-beefsteak-tomatoes"),
(11, 1, 1, "Plum Roma San Marzano Tomatoes", "Tasty.", "nobsc-plum-roma-san-marzano-tomatoes"),

(11, 1, 1, "Cherry Tomatoes", "Tasty.", "nobsc-cherry-tomatoes"),
(2, 1, 1, "Shrimp", "Tasty.", "nobsc-shrimp"),
(2, 1, 1, "Crab", "Tasty.", "nobsc-crab"),
(1, 1, 1, "Tuna", "Tasty.", "nobsc-tuna"),
(1, 1, 1, "Salmon", "Tasty.", "nobsc-salmon"),
(1, 1, 1, "Tilapia", "Tasty.", "nobsc-tilapia"),
(1, 1, 1, "Pollock", "Tasty.", "nobsc-pollock"),
(1, 1, 1, "Catfish", "Tasty.", "nobsc-catfish"),
(1, 1, 1, "Cod", "Tasty.", "nobsc-cod"),
(2, 1, 1, "Clams", "Tasty.", "nobsc-clams"),

(16, 1, 1, "Basil", "Tasty.", "nobsc-basil"),
(16, 1, 1, "Cilantro", "Tasty.", "nobsc-cilantro"),
(16, 1, 1, "Fenugreek", "Tasty.", "nobsc-fenugreek"),
(16, 1, 1, "Parsley", "Tasty.", "nobsc-parsley"),
(16, 1, 1, "Rosemary", "Tasty.", "nobsc-rosemary"),
(16, 1, 1, "Sage", "Tasty.", "nobsc-sage"),
(16, 1, 1, "Thyme", "Tasty.", "nobsc-thyme"),
(15, 1, 1, "Ancho Pepper", "Tasty.", "nobsc-ancho-pepper"),
(15, 1, 1, "Arbol Pepper", "Tasty.", "nobsc-arbol-pepper"),
(15, 1, 1, "Cascabel Pepper", "Tasty.", "nobsc-cascabel-pepper"),

(15, 1, 1, "Guajillo Pepper", "Tasty.", "nobsc-guajillo-pepper"),
(15, 1, 1, "Morita Pepper", "Tasty.", "nobsc-morita-pepper"),
(15, 1, 1, "Mulato Pepper", "Tasty.", "nobsc-mulato-pepper"),
(15, 1, 1, "Pasilla Pepper", "Tasty.", "nobsc-pasilla-pepper"),
(15, 1, 1, "Pulla Pepper", "Tasty.", "nobsc-pulla-pepper"),
(15, 1, 1, "Celery Seeds", "Tasty.", "nobsc-celery-seeds"),
(15, 1, 1, "Cinnamon", "Tasty.", "nobsc-cinnamon"),
(15, 1, 1, "Ground Cinnamon", "Tasty.", "nobsc-ground-cinnamon"),
(15, 1, 1, "Cloves", "Tasty.", "nobsc-cloves"),
(15, 1, 1, "Ground Cloves", "Tasty.", "nobsc-ground-cloves"),

(15, 1, 1, "Cumin Seeds", "Tasty.", "nobsc-cumin-seeds"),
(15, 1, 1, "Cumin Powder", "Tasty.", "nobsc-cumin-powder"),
(15, 1, 1, "Fennel Seeds", "Tasty.", "nobsc-fennel-seeds"),
(15, 1, 1, "Garlic", "Tasty.", "nobsc-garlic"),
(15, 1, 1, "Garlic Powder", "Tasty.", "nobsc-garlic-powder"),
(15, 1, 1, "Ginger", "Tasty.", "nobsc-ginger"),
(15, 1, 1, "Ginger Powder", "Tasty.", "nobsc-ginger-powder"),
(15, 1, 1, "Shallots", "Tasty.", "nobsc-shallots"),
(15, 1, 1, "Turmeric", "Tasty.", "nobsc-turmeric"),
(15, 1, 1, "Turmeric Powder", "Tasty.", "nobsc-turmeric-powder"),

(10, 1, 1, "Black Turtle Beans", "Tasty.", "nobsc-black-turtle-beans"),
(10, 1, 1, "Garbanzo Beans Chickpeas", "Tasty.", "nobsc-garbanzo-beans-chickpeas"),
(10, 1, 1, "Great Northern Beans", "Tasty.", "nobsc-great-northern-beans"),
(10, 1, 1, "Pinto Beans", "Tasty.", "nobsc-pinto-beans"),
(10, 1, 1, "Red Kidney Beans", "Tasty.", "nobsc-red-kidney-beans"),
(10, 1, 1, "Split Peas", "Tasty.", "nobsc-split-peas")
(4, 1, 1, "Bacon", "Tasty.", "nobsc-bacon"),
(5, 1, 1, "Chicken Wings", "Tasty.", "nobsc-raw-chicken-wings"),
(6, 1, 1, "Eggs", "Tasty.", "nobsc-eggs"),
(7, 1, 1, "Cream", "Tasty.", "nobsc-cream"),

(8, 1, 1, "Coconut", "Tasty.", "nobsc-coconut"),
(9, 1, 1, "Potatoes", "Tasty.", "nobsc-potatoes"),
(17, 1, 1, "Balsamic Vinegar", "Tasty.", "nobsc-balsamic-vinegar"),
(18, 1, 1, "Tobasco Sauce", "Tasty.", "nobsc-tobasco-sauce"),
(7, 1, 1, "Butter", "Tasty.", "nobsc-butter");