INSERT INTO nobsc_equipment
(equipment_type_id, author_id, owner_id, equipment_name, equipment_description, equipment_image)
VALUES
(2, 1, 1, "Chef''s Knife", "It works.", "nobsc-chefs-knife"),
(2, 1, 1, "Cutting Board", "It works.", "nobsc-cutting-board"),
(2, 1, 1, "Y Peeler", "It works.", "nobsc-y-peeler"),
(3, 1, 1, "Wooden Spoon", "It works.", "nobsc-wooden-spoon"),
(2, 1, 1, "Serated Knife", "It works.", "nobsc-serated-knife"),
(2, 1, 1, "Rubber Spatula", "It works.", "nobsc-rubber-spatula"),
(2, 1, 1, "Whisk", "It works.", "nobsc-whisk"),
(2, 1, 1, "Pepper Mill", "It works.", "nobsc-pepper-mill"),
(2, 1, 1, "Can Opener", "It works.", "nobsc-can-opener"),
(2, 1, 1, "Side Peeler", "It works.", "nobsc-side-peeler"),

(2, 1, 1, "Box Grater", "It works.", "nobsc-box-grater"),
(2, 1, 1, "Small Mixing Bowl", "It works.", "nobsc-small-mixing-bowl"),
(2, 1, 1, "Medium Mixing Bowl", "It works.", "nobsc-medium-mixing-bowl"),
(2, 1, 1, "Large Mixing Bowl", "It works.", "nobsc-large-mixing-bowl"),
(2, 1, 1, "Salad Spinner", "It works.", "nobsc-salad-spinner"),
(2, 1, 1, "Dry Measuring Cups", "It works.", "nobsc-dry-measuring-cups"),
(2, 1, 1, "Liquid Measuring Cups", "It works.", "nobsc-liquid-measuring-cups"),
(2, 1, 1, "Measuring Spoons", "It works.", "nobsc-measuring-spoons"),
(2, 1, 1, "Measuring Pitcher", "It works.", "nobsc-measuring-pitcher"),
(2, 1, 1, "Digital Scale", "It works.", "nobsc-digital-scale"),

(2, 1, 1, "Handheld Mixer", "It works.", "nobsc-handheld-mixer"),
(2, 1, 1, "Blender", "It works.", "nobsc-blender"),
(2, 1, 1, "Immersion Blender", "It works.", "nobsc-immersion-blender"),
(2, 1, 1, "Parchment Paper", "It works.", "nobsc-parchment-paper"),
(2, 1, 1, "Plastic Wrap", "It works.", "nobsc-plastic-wrap"),
(2, 1, 1, "Aluminum Foil", "It works.", "nobsc-aluminum-foil"),
(2, 1, 1, "Ceramic Stone", "It works.", "nobsc-ceramic-stone"),
(2, 1, 1, "Cheesecloth", "It works.", "nobsc-cheesecloth"),
(3, 1, 1, "Coffee Maker", "It works.", "nobsc-coffee-maker"),
(3, 1, 1, "Tea Pot", "It works.", "nobsc-tea-pot"),

(3, 1, 1, "Small Stainless Steel Skillet", "It works.", "nobsc-small-stainless-steel-skillet"),
(3, 1, 1, "Large Stainless Steel Skillet", "It works.", "nobsc-large-stainless-steel-skillet"),
(3, 1, 1, "Stainless Steel Lidded Saute Pan", "It works.", "nobsc-stainless-steel-lidded-saute-pan"),
(3, 1, 1, "Dutch Oven", "It works.", "nobsc-dutch-oven"),
(3, 1, 1, "Small Cast-Iron Skillet", "It works.", "nobsc-small-cast-iron-skillet"),
(3, 1, 1, "Large Cast-Iron Skillet", "It works.", "nobsc-large-cast-iron-skillet"),
(3, 1, 1, "Small Sauce Pan", "It works.", "nobsc-small-sauce-pan"),
(3, 1, 1, "Medium Sauce Pan", "It works.", "nobsc-medium-sauce-pan"),
(3, 1, 1, "Medium Stock Pot", "It works.", "nobsc-medium-stock-pot"),
(3, 1, 1, "Large Stock Pot", "It works.", "nobsc-large-stock-pot"),

(3, 1, 1, "Glass Baking Dish", "It works.", "nobsc-glass-baking-dish"),
(3, 1, 1, "Sturdy Baking Sheet", "It works.", "nobsc-sturdy-baking-dish"),
(3, 1, 1, "Small Gratin Dish", "It works.", "nobsc-small-gratin-dish"),
(3, 1, 1, "Large Gratin Dish", "It works.", "nobsc-large-gratin-dish"),
(3, 1, 1, "Oven Mitts", "It works.", "nobsc-oven-mitts"),
(3, 1, 1, "Splatter Screen", "It works.", "nobsc-splatter-screen"),
(3, 1, 1, "Colander", "It works.", "nobsc-colander"),
(3, 1, 1, "Mesh Strainer", "It works.", "nobsc-mesh-strainer"),
(3, 1, 1, "Tongs", "It works.", "nobsc-tongs"),
(3, 1, 1, "Slotted Spoon", "It works.", "nobsc-slotted-spoon"),

(3, 1, 1, "Serving Spoon", "It works.", "nobsc-serving-spoon"),
(3, 1, 1, "Spider", "It works.", "nobsc-spider"),
(3, 1, 1, "Sturdy Spatula", "It works.", "nobsc-sturdy-spatula"),
(3, 1, 1, "Fish Spatula", "It works.", "nobsc-fish-spatula"),
(3, 1, 1, "Ladle", "It works.", "nobsc-ladle");