import { uuidv7 } from 'uuidv7';
import * as fs from 'fs';

const data = [
  [1, "",                    "Tuna",                                     "tuna"],
  [1, "",                    "Salmon",                                   "salmon"],
  [1, "",                    "Tilapia",                                  "tilapia"],
  [1, "",                    "Pollock",                                  "pollock"],
  [1, "",                    "Catfish",                                  "catfish"],
  [1, "",                    "Cod",                                      "cod"],
  [2, "",                    "Clams",                                    "clams"],
  [2, "",                    "Crab",                                     "crab"],
  [2, "",                    "Shrimp",                                   "shrimp"],
  [3, "",                    "Chuck Seven Bone Roast",                   "chuck-7-bone-roast"],
  [3, "",                    "Chuck Seven Bone Steak",                   "chuck-7-bone-steak"],
  [3, "",                    "Chuck Arm Roast",                          "chuck-arm-roast"],
  [3, "Boneless",            "Chuck Arm Roast",                          "chuck-arm-rost-boneless"],
  [3, "",                    "Chuck Arm Steak",                          "chuck-arm-steak"],
  [3, "Boneless",            "Chuck Arm Steak",                          "chuck-arm-steak-boneless"],
  [3, "",                    "Chuck Blade Roast",                        "chuck-blade-roast"],
  [3, "",                    "Chuck Blade Steak",                        "chuck-blade-steak"],
  [3, "Boneless",            "Chuck Blade Steak",                        "chuck-blade-steak-boneless"],
  [3, "Cap Off",             "Chuck Blade Steak",                        "chuck-blade-steak-cap-off"],
  [3, "",                    "Chuck Cross Rib Roast",                    "chuck-cross-rib-roast"],
  [3, "Boneless",            "Chuck Cross Rib Roast",                    "chuck-cross-rib-roast-boneless"],
  [3, "",                    "Chuck Eye Edge Roast",                     "chuck-eye-edge-roast"],
  [3, "Boneless",            "Chuck Eye Roast",                          "chuck-eye-roast-steak"],
  [3, "Boneless",            "Chuck Eye Steak",                          "chuck-eye-steak-boneless"],
  [3, "",                    "Chuck Flanken Style Ribs",                 "chuck-flanken-style-ribs"],
  [3, "Boneless",            "Chuck Flanken Style Ribs",                 "chuck-flanken-style-ribs-boneless"],
  [3, "",                    "Chuck Flat Ribs",                          "chuck-flat-ribs"],
  [3, "",                    "Chuck Mock Tender Roast",                  "chuck-mock-tender-roast"],
  [3, "",                    "Chuck Mock Tender Steak",                  "chuck-mock-tender-steak"],
  [3, "",                    "Chuck Neck Roast",                         "chuck-neck-roast"],
  [3, "Boneless",            "Chuck Neck Roast",                         "chuck-neck-roast-boneless"],
  [3, "Boneless",            "Chuck Roast",                              "chuck-roast-boneless"],
  [3, "",                    "Chuck Short Ribs",                         "chuck-short-ribs"],
  [3, "Boneless",            "Chuck Short Ribs",                         "chuck-short-ribs-boneless"],
  [3, "",                    "Chuck Shoulder Center Steak Ranch Steak",  "chuck-shoulder-center-steak-ranch-steak"],
  [3, "",                    "Chuck Shoulder Roast",                     "chuck-shoulder-roast"],
  [3, "Boneless",            "Chuck Shoulder Roast",                     "chuck-shoulder-roast-boneless"],
  [3, "Boneless",            "Chuck Shoulder Steak",                     "chuck-shoulder-steak-boneless"],
  [3, "",                    "Chuck Shoulder Tender",                    "chuck-shoulder-tender"],
  [3, "",                    "Chuck Shoulder Tender Medallions",         "chuck-shoulder-tender-medallions"],
  [3, "Boneless",            "Chuck Shoulder Top Blade Roast",           "chuck-shoulder-top-blade-roast-boneless"],
  [3, "Boneless",            "Chuck Shoulder Top Blade Steak",           "chuck-shoulder-top-blade-steak-boneless"],
  [3, "",                    "Chuck Shoulder Top Blade Steak Flat Iron", "chuck-shoulder-top-blade-steak-flat-iron"],
  [3, "",                    "Chuck Top Blade Roast",                    "chuck-top-blade-roast"],
  [3, "Bone In",             "Chuck Top Blade Steak",                    "chuck-top-blade-steak-bone-in"],
  [3, "",                    "Chuck Under Blade Roast",                  "chuck-under-blade-roast"],
  [3, "Boneless",            "Chuck Under Blade Roast",                  "chuck-under-blade-roast-boneless"],
  [3, "",                    "Chuck Under Blade Steak",                  "chuck-under-blade-steak"],
  [3, "Boneless",            "Chuck Under Blade Steak",                  "chuck-under-blade-steak-boneless"],
  [3, "",                    "Round Bottom Round Roast",                 "round-bottom-round-roast"],
  [3, "",                    "Round Bottom Round Roast Triangle Roast",  "round-bottom-round-roast-triangle-roast"],
  [3, "",                    "Round Bottom Round Rump Roast",            "round-bottom-round-rump-roast"],
  [3, "",                    "Round Bottom Round Steak",                 "round-bottom-round-steak"],
  [3, "",                    "Round Bottom Round Steak Western Griller", "round-bottom-round-steak-western-griller"],
  [3, "",                    "Round Eye Round Roast",                    "round-eye-round-roast"],
  [3, "",                    "Round Eye Round Steak",                    "round-eye-round-steak"],
  [3, "",                    "Round Heel of Round",                      "round-heel-of-round"],
  [3, "",                    "Round Sirloin Tip Center Roast",           "round-sirloin-tip-center-roast"],
  [3, "",                    "Round Sirloin Tip Center Steak",           "round-sirloin-tip-center-steak"],
  [3, "",                    "Round Sirloin Tip Side Steak",             "round-sirloin-tip-side-steak"],
  [3, "",                    "Round Steak",                              "round-steak"],
  [3, "Boneless",            "Round Steak",                              "round-steak-boneless"],
  [3, "",                    "Round Tip Roast",                          "round-tip-roast"],
  [3, "Cap Off",             "Round Tip Roast",                          "round-tip-roast-cap-off"],
  [3, "",                    "Round Tip Steak",                          "round-tip-steak"],
  [3, "Cap Off",             "Round Tip Steak",                          "round-tip-steak-cap-off"],
  [3, "",                    "Round Top Round Roast",                    "round-top-round-roast"],
  [3, "Cap Off",             "Round Top Round Roast",                    "round-top-round-roast-cap-off"],
  [3, "",                    "Round Top Round Steak",                    "round-top-round-steak"],
  [3, "",                    "Round Top Round Steak Butterflied",        "round-top-round-steak-butterflied"],
  [3, "",                    "Round Top Round Steak First Cut",          "round-top-round-steak-first-cut"],
  [3, "",                    "Loin Ball Tip Roast",                      "loin-ball-tip-roast"],
  [3, "",                    "Loin Ball Tip Steak",                      "loin-ball-tip-steak"],
  [3, "",                    "Loin Flap Meat Steak",                     "loin-flap-meat-steak"],
  [3, "",                    "Loin Porterhouse Steak",                   "loin-porterhouse-steak"],
  [3, "",                    "Loin Shell Sirloin Steak",                 "loin-shell-sirloin-steak"],
  [3, "",                    "Loin Sirloin Steak",                       "loin-sirloin-steak"],
  [3, "",                    "Loin T Bone Steak",                        "loin-t-bone-steak"],
  [3, "",                    "Loin Tenderloin Roast",                    "loin-tenderloin-roast"],
  [3, "",                    "Loin Tenderloin Steak",                    "loin-tenderloin-steak"],
  [3, "",                    "Loin Top Loin Roast",                      "loin-top-loin-roast"],
  [3, "Boneless",            "Loin Top Loin Roast",                      "loin-top-loin-roast-boneless"],
  [3, "",                    "Loin Top Loin Steak",                      "loin-top-loin-steak"],
  [3, "Boneless",            "Loin Top Loin Steak",                      "loin-top-loin-steak-boneless"],
  [3, "Boneless",            "Loin Top Sirloin Roast",                   "loin-top-sirloin-roast-boneless"],
  [3, "Boneless Cap Off",    "Loin Top Sirloin Roast",                   "loin-top-sirloin-roast-boneless-cap-off"],
  [3, "Boneless",            "Loin Top Sirloin Steak",                   "loin-top-sirloin-steak-boneless"],
  [3, "Boneless Cap Off",    "Loin Top Sirloin Steak",                   "loin-top-sirloin-steak-boneless-cap-off"],
  [3, "",                    "Loin Tri Tip Roast",                       "loin-tri-tip-roast"],
  [3, "",                    "Loin Tri Tip Steak",                       "loin-tri-tip-steak"],
  [3, "",                    "Shank Cross Cut",                          "shank-cross-cut"],
  [3, "Boneless",            "Shank Cross Cut",                          "shank-cross-cut-boneless"],
  [3, "",                    "Plate Skirt Steak",                        "plate-skirt-steak"],
  [3, "",                    "Flank Steak",                              "flank-flank-steak"],
  [3, "",                    "Ground Beef",                              "ground-beef"],
  [3, "",                    "Back Ribs",                                "back-ribs"],
  [3, "Boneless",            "Rib Cap Meat",                             "rib-cap-meat-boneless"],
  [3, "",                    "Rib Extra Trim Roast Large End",           "rib-extra-trim-roast-large-end"],
  [3, "",                    "Ribeye Roast",                             "ribeye-roast"],
  [3, "Lip On Bone In",      "Ribeye Roast",                             "ribeye-roast-lip-on-bone-in"],
  [3, "Lip On Boneless",     "Ribeye Roast",                             "ribeye-roast-lip-on-boneless"],
  [3, "",                    "Ribeye Steak",                             "ribeye-steak"],
  [3, "Lip On Bone In",      "Ribeye Steak",                             "ribeye-steak-lip-on-bone-in"],
  [3, "Lip On Boneless",     "Ribeye Steak",                             "ribeye-steak-lip-on-boneless"],
  [3, "",                    "Rib Roast Large End",                      "rib-roast-large-end"],
  [3, "Boneless",            "Rib Roast Large End",                      "rib-roast-large-end-boneless"],
  [3, "",                    "Rib Roast Small End",                      "rib-roast-small-end"],
  [3, "Boneless",            "Rib Roast Small End",                      "rib-roast-small-end-boneless"],
  [3, "Boneless",            "Rib Rolled Cap Pot Roast",                 "rib-rolled-cap-pot-roast-boneless"],
  [3, "",                    "Rib Short Ribs",                           "rib-short-ribs"],
  [3, "Boneless",            "Rib Short Ribs",                           "rib-short-ribs-boneless"],
  [3, "",                    "Rib Steak Large End",                      "rib-steak-large-end"],
  [3, "",                    "Rib Steak Small End",                      "rib-steak-small-end"],
  [3, "Boneless",            "Rib Steak Small End",                      "rib-steak-small-end-boneless"],
  [4, "",                    "Bacon",                                    "bacon"],
  [5, "Bone In",             "Chicken Breasts",                          "raw-chicken-wings"],
  [5, "Boneless",            "Chicken Breasts",                          "raw-chicken-wings"],
  [5, "",                    "Chicken Breasts",                          "raw-chicken-wings"],
  [5, "",                    "Chicken Tenderloins",                      "raw-chicken-wings"],
  [5, "Bone In",             "Chicken Thighs",                           "raw-chicken-wings"],
  [5, "Boneless",            "Chicken Thighs",                           "raw-chicken-wings"],
  [5, "",                    "Chicken Thighs",                           "raw-chicken-wings"],
  [5, "",                    "Chicken Wings",                            "raw-chicken-wings"],
  [6, "",                    "Extra Large Eggs",                         "eggs"],
  [6, "",                    "Large Eggs",                               "eggs"],
  [6, "",                    "Medium Eggs",                              "eggs"],
  [7, "Salted",              "Butter",                                   "butter"],
  [7, "Unsalted",            "Butter",                                   "butter"],
  [7, "",                    "Cream",                                    "cream"],
  [8, "",                    "Coconut",                                  "coconut"],
  [9, "Corn",                "Starch",                                   "eggs"],
  [9, "Potato",              "Starch",                                   "eggs"],
  [9, "All-Purpose",         "Flour",                                    "eggs"],
  [10, "Black Turtle",       "Beans",                                    "black-turtle-beans"],
  [10, "Garbanzo",           "Beans",                                    "garbanzo-beans-chickpeas"],
  [10, "Great Northern",     "Beans",                                    "great-northern-beans"],
  [10, "Pinto",              "Beans",                                    "pinto-beans"],
  [10, "Red Kidney",         "Beans",                                    "red-kidney-beans"],
  [10, "",                   "Split Peas",                               "split-peas"],
  [11, "All Blue",           "Potatoes",                                 "potatoes"],
  [11, "Austrian Crescent",  "Potatoes",                                 "potatoes"],
  [11, "French Fingerling",  "Potatoes",                                 "potatoes"],
  [11, "Kennebec",           "Potatoes",                                 "potatoes"],
  [11, "LaRette",            "Potatoes",                                 "potatoes"],
  [11, "Norland Red",        "Potatoes",                                 "potatoes"],
  [11, "Purple Majesty",     "Potatoes",                                 "potatoes"],
  [11, "Red Gold",           "Potatoes",                                 "potatoes"],
  [11, "Red Thumb",          "Potatoes",                                 "potatoes"],
  [11, "Russet Ranger",      "Potatoes",                                 "potatoes"],
  [11, "Russet Burbank",     "Potatoes",                                 "potatoes"],
  [11, "Russet Norkotah",    "Potatoes",                                 "potatoes"],
  [11, "Russet Umatilla",    "Potatoes",                                 "potatoes"],
  [11, "Russian Banana",     "Potatoes",                                 "potatoes"],
  [11, "Yukon Gold",         "Potatoes",                                 "potatoes"],
  [11, "",                   "Potatoes",                                 "potatoes"],
  [11, "",                   "Broccoli",                                 "broccoli"],
  [11, "",                   "Brussels Sprouts",                         "brussels-sprouts"],
  [11, "",                   "Bok Choy",                                 "bok-choy"],
  [11, "Green",              "Cabbage",                                  "green-cabbage"],
  [11, "Red",                "Cabbage",                                  "red-cabbage"],
  [11, "Napa",               "Cabbage",                                  "napa-cabbage-chinese-cabbage"],
  [11, "Savoy",              "Cabbage",                                  "savoy-cabbage"],
  [11, "",                   "Cauliflower",                              "cauliflower"],
  [11, "",                   "Kohlrabi",                                 "kohlrabi"],
  [11, "",                   "Collard Greens",                           "collard-greens"],
  [11, "",                   "Turnip Greens",                            "turnip-greens"],
  [11, "",                   "Pak Choy Baby Bok Choy",                   "pak-choy-baby-bok-choy"],
  [11, "",                   "Zucchini",                                 "zucchini"],
  [11, "Standard Slicing",   "Cucumber",                                 "standard-slicing-cucumber"],
  [11, "Purple",             "Eggplant",                                 "purple-eggplant"],
  [11, "White",              "Eggplant",                                 "white-eggplant"],
  [11, "Japanese",           "Eggplant",                                 "japanese-eggplant"],
  [11, "",                   "Pumpkin",                                  "pumpkin"],
  [11, "Acorn",              "Squash",                                   "acorn-squash"],
  [11, "Butternut",          "Squash",                                   "butternut-squash"],
  [11, "Hubbard",            "Squash",                                   "hubbard-squash"],
  [11, "Spaghetti",          "Squash",                                   "spaghetti-squash"],
  [11, "Delicata",           "Squash",                                   "delicata-squash"],
  [11, "Boston",             "Lettuce",                                  "boston-lettuce"],
  [11, "Bibb",               "Lettuce",                                  "bibb-lettuce"],
  [11, "Iceberg",            "Lettuce",                                  "iceberg-lettuce"],
  [11, "Romaine",            "Lettuce",                                  "romaine-lettuce"],
  [11, "Green Leaf",         "Lettuce",                                  "green-leaf-lettuce"],
  [11, "Oak Leaf",           "Lettuce",                                  "oak-leaf-lettuce"],
  [11, "Red Leaf",           "Lettuce",                                  "red-leaf-lettuce"],
  [11, "",                   "Arugula Rocket",                           "arugula-rocket"],
  [11, "",                   "Belgian Endive",                           "belgian-endive"],
  [11, "",                   "Frisee",                                   "frisee"],
  [11, "",                   "Escarole",                                 "escarole"],
  [11, "",                   "Mache Lambs Lettuce",                      "mache-lambs-lettuce"],
  [11, "",                   "Radicchio",                                "radicchio"],
  [11, "",                   "Watercress",                               "watercress"],
  [11, "Baby",               "Spinach",                                  "baby-spinach"],
  [11, "Frozen",             "Spinach",                                  "spinach"],
  [11, "",                   "Spinach",                                  "spinach"],
  [11, "",                   "Swiss Chard",                              "swiss-chard"],
  [11, "",                   "Beet Greens",                              "beet-greens"],
  [11, "",                   "Dandelion Greens",                         "dandelion-greens"],
  [11, "",                   "Mustard Greens",                           "mustard-greens"],
  [11, "Shiitake",           "Mushrooms",                                "shiitake-mushrooms"],
  [11, "Cremini",            "Mushrooms",                                "cremini-mushrooms"],
  [11, "Portobello",         "Mushrooms",                                "portobello-mushrooms"],
  [11, "",                   "Mushrooms",                                "mushrooms"],
  [11, "Globe",              "Onion",                                    "globe-onion"],
  [11, "Green",              "Onion",                                    "scallion-green-onion"],
  [11, "Spanish",            "Onion",                                    "spanish-onion"],
  [11, "Sweet",              "Onion",                                    "sweet-onion"],
  [11, "",                   "Onion",                                    "onion"],
  [11, "Pearl",              "Onions",                                   "pearl-onions"],
  [11, "",                   "Garlic",                                   "garlic"],
  [11, "",                   "Shallots",                                 "shallots"],
  [11, "",                   "Leek",                                     "leek"],
  [11, "Bell",               "Pepper",                                   "bell-pepper"],
  [11, "Poblano",            "Pepper",                                   "poblano-pepper"],
  [11, "Jalapeno",           "Pepper",                                   "jalapeno-pepper"],
  [11, "Serrano",            "Pepper",                                   "serrano-pepper"],
  [11, "Thai",               "Pepper",                                   "thai-pepper"],
  [11, "Habanero",           "Pepper",                                   "habanero-pepper"],
  [11, "Winterbor",          "Kale",                                     "winterbor-kale-curly-kale"],
  [11, "Red Russian",        "Kale",                                     "red-russian-kale"],
  [11, "",                   "Kale",                                     "kale"],
  [11, "",                   "Green Beans",                              "green-beans"],
  [11, "",                   "Celery",                                   "celery"],
  [11, "",                   "Asparagus",                                "asparagus"],
  [11, "Green",              "Peas",                                     "green-peas"],
  [11, "Snow",               "Peas",                                     "snowpeas"],
  [11, "Sugar Snap",         "Peas",                                     "sugar-snap-peas"],
  [11, "",                   "Carrots",                                  "carrots"],
  [11, "",                   "Parsnips",                                 "parsnips"],
  [11, "White",              "Turnips",                                  "white-turnips"],
  [11, "",                   "Turnips",                                  "turnips"],
  [11, "French",             "Radishes",                                 "french-radishes"],
  [11, "",                   "Radishes",                                 "radishes"],
  [11, "Baby Gold",          "Beets",                                    "baby-gold-beets"],
  [11, "Red",                "Beets",                                    "red-beets"],
  [11, "",                   "Beets",                                    "beets"],
  [11, "",                   "Daikon",                                   "daikon"],
  [11, "",                   "Horseradish",                              "horseradish"],
  [11, "",                   "Rutabaga",                                 "rutabaga"],
  [11, "",                   "Ginger",                                   "ginger"],
  [11, "",                   "Sunchoke Jerusalem Artichoke",             "sunchoke-jerusalem-artichoke"],
  [11, "",                   "Fennel",                                   "fennel"],
  [11, "",                   "Tomatillo",                                "tomatillo"],
  [11, "Standard Beefsteak", "Tomatoes",                                 "standard-beefsteak-tomatoes"],
  [11, "Plum Roma",          "Tomatoes",                                 "plum-roma-san-marzano-tomatoes"],
  [11, "Plum San Marzano",   "Tomatoes",                                 "plum-roma-san-marzano-tomatoes"],
  [11, "Sungold",            "Tomatoes",                                 "cherry-tomatoes"],
  [11, "Cherry",             "Tomatoes",                                 "cherry-tomatoes"],
  [11, "Grape",              "Tomatoes",                                 "grape-tomatoes"],
  [11, "",                   "Tomatoes",                                 "cherry-tomatoes"],
  [12, "Ambrosia",           "Apple",                                    "apple"],
  [12, "Baldwin",            "Apple",                                    "apple"],
  [12, "Braeburn",           "Apple",                                    "apple"],
  [12, "Cameo",              "Apple",                                    "apple"],
  [12, "Cortland",           "Apple",                                    "apple"],
  [12, "Cosmic Crisp",       "Apple",                                    "apple"],
  [12, "Empire",             "Apple",                                    "apple"],
  [12, "Enterprise",         "Apple",                                    "apple"],
  [12, "Fuji",               "Apple",                                    "apple"],
  [12, "Gala",               "Apple",                                    "apple"],
  [12, "Golden Delicious",   "Apple",                                    "apple"],
  [12, "Granny Smith",       "Apple",                                    "apple"],
  [12, "Honeycrisp",         "Apple",                                    "apple"],
  [12, "Idared",             "Apple",                                    "apple"],
  [12, "Jazz",               "Apple",                                    "apple"],
  [12, "Jonagold",           "Apple",                                    "apple"],
  [12, "Jonathan",           "Apple",                                    "apple"],
  [12, "Liberty",            "Apple",                                    "apple"],
  [12, "Macoun",             "Apple",                                    "apple"],
  [12, "McIntosh Red",       "Apple",                                    "apple"],
  [12, "Melrose",            "Apple",                                    "apple"],
  [12, "Opal",               "Apple",                                    "apple"],
  [12, "Ozark Gold",         "Apple",                                    "apple"],
  [12, "Pinata",             "Apple",                                    "apple"],
  [12, "Pink Lady",          "Apple",                                    "apple"],
  [12, "Pristine",           "Apple",                                    "apple"],
  [12, "Red Delicious",      "Apple",                                    "apple"],
  [12, "Rome",               "Apple",                                    "apple"],
  [12, "Spartan",            "Apple",                                    "apple"],
  [12, "Stayman",            "Apple",                                    "apple"],
  [12, "SweeTango",          "Apple",                                    "apple"],
  [12, "Winesap",            "Apple",                                    "apple"],
  [12, "",                   "Apple",                                    "apple"],
  [12, "",                   "Apricot",                                  "apricot"],
  [12, "",                   "Banana",                                   "banana"],
  [12, "",                   "Blackberries",                             "blackberries"],
  [12, "",                   "Blueberries",                              "blueberries"],
  [12, "",                   "Cherries",                                 "cherries"],
  [12, "Dried",              "Cranberries",                              "cranberries"],
  [12, "",                   "Cranberries",                              "cranberries"],
  [12, "Concord",            "Grapes",                                   "grapes"],
  [12, "Flame",              "Grapes",                                   "grapes"],
  [12, "Moon Drop",          "Grapes",                                   "grapes"],
  [12, "Ruby",               "Grapes",                                   "grapes"],
  [12, "Thompson",           "Grapes",                                   "grapes"],
  [12, "",                   "Grapes",                                   "grapes"],
  [12, "",                   "Guava",                                    "guava"],
  [12, "",                   "Kiwi",                                     "kiwi"],
  [12, "",                   "Mango",                                    "mango"],
  [12, "",                   "Watermelon",                               "watermelon"],
  [12, "",                   "Nectarine",                                "nectarine"],
  [12, "",                   "Papaya",                                   "papaya"],
  [12, "",                   "Peach",                                    "peach"],
  [12, "Anjou Green",        "Pear",                                     "pear"],
  [12, "Anjou Red",          "Pear",                                     "pear"],
  [12, "Asian",              "Pear",                                     "pear"],
  [12, "Bartlett",           "Pear",                                     "pear"],
  [12, "Bosc",               "Pear",                                     "pear"],
  [12, "Comice",             "Pear",                                     "pear"],
  [12, "Concord",            "Pear",                                     "pear"],
  [12, "Forelle",            "Pear",                                     "pear"],
  [12, "French Butter",      "Pear",                                     "pear"],
  [12, "Seckel",             "Pear",                                     "pear"],
  [12, "Taylor\'s Gold",     "Pear",                                     "pear"],
  [12, "",                   "Pear",                                     "pear"],
  [12, "",                   "Pineapple",                                "pineapple"],
  [12, "",                   "Orange",                                   "orange"],
  [12, "",                   "Raspberries",                              "raspberries"],
  [12, "",                   "Strawberries",                             "strawberries"],
  [12, "",                   "Tangerine",                                "tangerine"],
  [12, "",                   "Tangelo",                                  "tangelo"],
  [12, "",                   "Blood Orange",                             "blood-orange"],
  [12, "",                   "White Grapefruit",                         "white-grapefruit"],
  [12, "",                   "Pink Grapefruit",                          "pink-grapefruit"],
  [12, "",                   "Honeydew",                                 "honeydew"],
  [12, "",                   "Cantaloupe",                               "cantaloupe"],
  [12, "Italian",            "Plum",                                     "italian-plum"],
  [12, "",                   "Plum",                                     "plum"],
  [12, "",                   "Pomegranate",                              "pomegranate"],
  [13, "",                   "Almonds",                                  "almonds"],
  [13, "",                   "Brazil Nuts",                              "almonds"],
  [13, "",                   "Cashews",                                  "cashews"],
  [13, "",                   "Hazelnuts",                                "almonds"],
  [13, "",                   "Macadamia Nuts",                           "almonds"],
  [13, "",                   "Peacans",                                  "almonds"],
  [13, "",                   "Peanuts",                                  "almonds"],
  [13, "",                   "Pine Nuts",                                "almonds"],
  [13, "",                   "Pistachios",                               "pistachios"],
  [13, "",                   "Walnuts",                                  "almonds"],
  [14, "",                   "Chia Seeds",                               "sesame-seeds"],
  [14, "",                   "Hemp Seeds",                               "sesame-seeds"],
  [14, "",                   "Poppy Seeds",                              "sesame-seeds"],
  [14, "",                   "Pumpkin Seeds",                            "pumpkin-seeds"],
  [14, "",                   "Sesame Seeds",                             "sesame-seeds"],
  [14, "",                   "Quinoa",                                   "sesame-seeds"],
  [15, "Ancho",              "Pepper",                                   "ancho-pepper"],
  [15, "Arbol",              "Pepper",                                   "arbol-pepper"],
  [15, "Cascabel",           "Pepper",                                   "cascabel-pepper"],
  [15, "Guajillo",           "Pepper",                                   "guajillo-pepper"],
  [15, "Morita",             "Pepper",                                   "morita-pepper"],
  [15, "Mulato",             "Pepper",                                   "mulato-pepper"],
  [15, "Pasilla",            "Pepper",                                   "pasilla-pepper"],
  [15, "Pulla",              "Pepper",                                   "pulla-pepper"],
  [15, "",                   "Celery Seeds",                             "celery-seeds"],
  [15, "",                   "Cinnamon",                                 "cinnamon"],
  [15, "",                   "Ground Cinnamon",                          "ground-cinnamon"],
  [15, "",                   "Cloves",                                   "cloves"],
  [15, "",                   "Ground Cloves",                            "ground-cloves"],
  [15, "",                   "Caraway Seeds",                            "cumin-seeds"],
  [15, "",                   "Cumin Seeds",                              "cumin-seeds"],
  [15, "",                   "Cumin Powder",                             "cumin-powder"],
  [15, "",                   "Fennel Seeds",                             "fennel-seeds"],
  [15, "",                   "Garlic",                                   "garlic"],
  [15, "",                   "Garlic Powder",                            "garlic-powder"],
  [15, "",                   "Ginger",                                   "ginger"],
  [15, "",                   "Ginger Powder",                            "ginger-powder"],
  [15, "",                   "Shallots",                                 "shallots"],
  [15, "",                   "Turmeric",                                 "turmeric"],
  [15, "",                   "Turmeric Powder",                          "turmeric-powder"],
  [16, "",                   "Basil",                                    "basil"],
  [16, "",                   "Cilantro",                                 "cilantro"],
  [16, "",                   "Fenugreek",                                "fenugreek"],
  [16, "",                   "Parsley",                                  "parsley"],
  [16, "",                   "Rosemary",                                 "rosemary"],
  [16, "",                   "Sage",                                     "sage"],
  [16, "",                   "Thyme",                                    "thyme"],
  [17, "Apple Cider",        "Vinegar",                                  "apple-cider-vinegar"],
  [17, "Balsamic",           "Vinegar",                                  "balsamic-vinegar"],
  [17, "Rice",               "Vinegar",                                  "rice-vinegar"],
  [18, "",                   "Fish Sauce",                               "fish-sauce"],
  [18, "Dark",               "Soy Sauce",                                "dark-soy-sauce"],
  [18, "Light",              "Soy Sauce",                                "light-soy-sauce"]
];

const NOBSC_USER_ID = "11111111-1111-1111-1111-111111111111";

const image_records = [];
const ingredient_records = [];

data.map(([
  ingredient_type_id,
  ingredient_variety,
  ingredient_name,
  image_filename
]) => {
  const image_id = uuidv7();

  image_records.push({
    image_id,
    image_filename,
    caption: `${ingredient_variety} ${ingredient_name}`,
    author_id: NOBSC_USER_ID,
    owner_id: NOBSC_USER_ID
  });

  ingredient_records.push({
    ingredient_id: uuidv7(),
    ingredient_type_id,
    owner_id: NOBSC_USER_ID,
    //ingredient_brand: "",
    ingredient_variety,
    ingredient_name,
    notes: "",
    image_id
  });
});

fs.writeFileSync(
  'generated-ingredient-images.json',
  JSON.stringify(image_records, null, 2),
  'utf-8'
);

console.log('ingredient images generated');

fs.writeFileSync(
  'generated-ingredients.json',
  JSON.stringify(ingredient_records, null, 2),
  'utf-8'
);

console.log('ingredients generated');
