name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - run: npm install

    #- run: npm run test -- --coverage --watchAll=false
    - run: docker-compose -f docker-compose.test.yml down
    - run: sleep 29s
    - run: docker system prune --all --force --volumes
    - run: sleep 29s
    - run: docker-compose -f docker-compose.test.yml up --build -d mysql-test
    - run: sleep 59s
    #- run: docker ps
    - run: docker cp ./dbdata/test.sql nobullshitcooking-api_mysql-test_1:test.sql
    - run: sleep 9s
    - run: docker exec -i nobullshitcooking-api_mysql-test_1 bash
    - run: ls
    #- run: docker exec nobullshitcooking-api_mysql-test_1 mysql -u root -p pass -e "SOURCE test.sql;"
    #- run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'mysql -u root -p pass </test.sql'
    #- run: sudo /etc/init.d/mysql start
    #- run: sudo systemctl start mysql
    #- run: sudo systemctl status mysql.service
    #- run: sudo rm /etc/mysql/my.cnf
    #- run: sudo service mysql status
    #- run: sudo service mysql start
    - run: sleep 29s
    #- run: docker logs nobullshitcooking-api_mysql-test_1
    #- run: mysql -u root -p pass
    #- run: DROP DATABASE nobsc;
    #- run: CREATE DATABASE nobsc;
    #- run: SOURCE test.sql;
    - run: quit
    #- run: exit
    - run: docker-compose -f docker-compose.test.yml down
    - run: sleep 29s
    - run: docker-compose -f docker-compose.test.yml up --build --exit-code-from nobsc-api-test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./coverage/
        name: codecov-umbrella
        #fail_ci_if_error: true

    timeout-minutes: 5