name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - run: npm install

    #- run: npm run test -- --coverage --watchAll=false
    - run: docker-compose -f docker-compose.test.yml down
    - run: sleep 10s
    - run: docker system prune --all --force --volumes
    - run: sleep 10s
    - run: docker-compose -f docker-compose.test.yml up --build -d mysql-test
    - run: sleep 40s
    - run: docker cp ./dbdata/test.sql nobullshitcooking-api_mysql-test_1:test.sql
    - run: sleep 3s
    - run: docker exec -i nobullshitcooking-api_mysql-test_1 bash
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'ls'
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c '/etc/init.d/mysqld restart --skip-grant-tables'
    - run: sleep 20s
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'mysql'
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'FLUSH PRIVILEGES;'
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c "ALTER USER 'root'@'localhost' IDENTIFIED BY 'pass'"
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c '/etc/init.d/mysqld restart'
    - run: sleep 20s
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'mysql -u root -p pass </test.sql'
    - run: sleep 15s
    #- run: docker logs nobullshitcooking-api_mysql-test_1
    #- run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'quit'
    - run: docker exec nobullshitcooking-api_mysql-test_1 /bin/sh -c 'exit'
    #- run: docker-compose -f docker-compose.test.yml down
    #- run: sleep 15s
    - run: docker-compose -f docker-compose.test.yml up --build --exit-code-from nobsc-api-test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./coverage/
        name: codecov-umbrella
        #fail_ci_if_error: true

    timeout-minutes: 5